Namespace Table.Man
    Public Class [Employee]
        ReadOnly Property TableName As String = "man_employee"
        ReadOnly Property S As String = "emp"
        ReadOnly Property C_EmployeeId As String = "employee_id"
        ReadOnly Property C_EmployeePosition As String = "employee_position"
        ReadOnly Property C_EmployeeNumber As String = "employee_number"
        ReadOnly Property C_EmployeeFullName As String = "employee_fullname"
        ReadOnly Property C_EmployeeNickname As String = "employee_nickname"
        ReadOnly Property C_EmployeePersonalIdNumber As String = "employee_personalidnumber"
        ReadOnly Property C_EmployeeGender As String = "employee_gender"
        ReadOnly Property C_EmployeeBirthDate As String = "employee_birthdate"
        ReadOnly Property C_EmployeeBirthPlace As String = "employee_birthplace"
        ReadOnly Property C_EmployeeAddress As String = "employee_address"
        ReadOnly Property C_EmployeeIsActive As String = "employee_isactive"
        ReadOnly Property C_EmployeeClient As String = "employee_client"
        ReadOnly Property C_EmployeeEmploymentType As String = "employee_employmenttype"
        ReadOnly Property C_EmployeeCompanyEmail As String = "employee_email"
        ReadOnly Property C_EmployeeToken As String = "employee_token"
        ReadOnly Property C_EmployeeDateCreated As String = "employee_datecreated"
        ReadOnly Property C_EmployeeDateLastUpdate As String = "employee_datelastupdate"
        ReadOnly Property P_EmployeeId As String = "@EmployeeId"
        ReadOnly Property P_EmployeePosition As String = "@EmployeePosition"
        ReadOnly Property P_EmployeeNumber As String = "@EmployeeNumber"
        ReadOnly Property P_EmployeeFullName As String = "@EmployeeFullName"
        ReadOnly Property P_EmployeeNickname As String = "@EmployeeNickname"
        ReadOnly Property P_EmployeePersonalIdNumber As String = "@EmployeePersonalIdNumber"
        ReadOnly Property P_EmployeeGender As String = "@EmployeeGender"
        ReadOnly Property P_EmployeeBirthDate As String = "@EmployeeBirthDate"
        ReadOnly Property P_EmployeeBirthPlace As String = "@EmployeeBirthPlace"
        ReadOnly Property P_EmployeeAddress As String = "@EmployeeAddress"
        ReadOnly Property P_EmployeeIsActive As String = "@EmployeeIsActive"
        ReadOnly Property P_EmployeeClient As String = "@EmployeeClient"
        ReadOnly Property P_EmployeeEmploymentType As String = "@EmployeeEmploymentType"
        ReadOnly Property P_EmployeeCompanyEmail As String = "@EmployeeCompanyEmail"
        ReadOnly Property P_EmployeeToken As String = "@EmployeeToken"
        ReadOnly Property P_EmployeeDateCreated As String = "@EmployeeDateCreated"
        ReadOnly Property P_EmployeeDateLastUpdate As String = "@EmployeeDateLastUpdate"
    End Class
End Namespace