Namespace Table.Man
    Public Class [Employee]
        ReadOnly Property TableName As String = "man_employee"
        ReadOnly Property S As String = "emp"
        ReadOnly Property C_EmployeeId As String = "employee_id"
        ReadOnly Property C_EmployeePosition As String = "employee_position"
        ReadOnly Property C_EmployeeNumber As String = "employee_number"
        ReadOnly Property C_EmployeeFullName As String = "employee_fullname"
        ReadOnly Property C_EmployeeNickname As String = "employee_nickname"
        ReadOnly Property C_EmployeePersonalIdNumber As String = "employee_personalidnumber"
        ReadOnly Property C_EmployeeGender As String = "employee_gender"
        ReadOnly Property C_EmployeeBirthDate As String = "employee_birthdate"
        ReadOnly Property C_EmployeeBirthPlace As String = "employee_birthplace"
        ReadOnly Property C_EmployeeAddress As String = "employee_address"
        ReadOnly Property C_EmployeeEmploymentType As String = "employee_employmenttype"
        ReadOnly Property C_EmployeeIsActive As String = "employee_isactive"
        ReadOnly Property P_EmployeeId As String = "@EmployeeId"
        ReadOnly Property P_EmployeeNumber As String = "@EmployeeNumber"
        ReadOnly Property P_EmployeeFullName As String = "@EmployeeFullName"
        ReadOnly Property P_EmployeeNickname As String = "@EmployeeNickname"
        ReadOnly Property P_EmployeePersonalIdNumber As String = "@EmployeePersonalIdNumber"
        ReadOnly Property P_EmployeeGender As String = "@EmployeeGender"
        ReadOnly Property P_EmployeeBirthDate As String = "@EmployeeBirthDate"
        ReadOnly Property P_EmployeeBirthPlace As String = "@EmployeeBirthPlace"
        ReadOnly Property P_EmployeeAddress As String = "@EmployeeAddress"
        ReadOnly Property P_EmployeeIsActive As String = "@EmployeeIsActive"
    End Class
End Namespace