Namespace Table.Sys
    Public Class [Settings]
        ReadOnly Property TableName As String = "sys_settings"
        ReadOnly Property S As String = "sett"
        ReadOnly Property C_SettingsId As String = "settings_id"
        ReadOnly Property C_SettingsShowProfile As String = "settings_showprofile"
        ReadOnly Property C_SettingsShowStorage As String = "settings_showstorage"
        ReadOnly Property C_SettingsShowWatermark As String = "settings_showwatermark"
        ReadOnly Property C_SettingsTextMark As String = "settings_textmark"
        ReadOnly Property C_SettingsTextMarkLength As String = "settings_textmarklength"
        ReadOnly Property C_SettingsShowRunningText As String = "settings_showrunningtext"
        ReadOnly Property C_SettingsUploadPhoto As String = "settings_uploadphoto"
        ReadOnly Property C_SettingsUploadPdf As String = "settings_uploadpdf"
        ReadOnly Property C_SettingsMinPasswordLength As String = "settings_minpasswordlength"
        ReadOnly Property C_SettingsStorageProvider As String = "settings_storageprovider"
        ReadOnly Property C_SettingsApiKey As String = "settings_apikey"
        ReadOnly Property C_SettingsApiSecret As String = "settings_apisecret"
        ReadOnly Property C_SettingsApiServiceUrl As String = "settings_apiserviceurl"
        ReadOnly Property C_SettingsStorageDb As String = "settings_storagedb"
        ReadOnly Property C_SettingsClient As String = "settings_client"
        ReadOnly Property P_SettingsId As String = "@SettingsId"
        ReadOnly Property P_SettingsShowProfile As String = "@SettingShowProfile"
        ReadOnly Property P_SettingsShowStorage As String = "@SettingsShowStorage"
        ReadOnly Property P_SettingsShowWatermark As String = "@SettingShowWatermark"
        ReadOnly Property P_SettingsTextMark As String = "@SettingsTextMark"
        ReadOnly Property P_SettingsTextMarkLength As String = "@SettingTextmarkLength"
        ReadOnly Property P_SettingsShowRunningText As String = "@SettingsShowRunningText"
        ReadOnly Property P_SettingsUploadPhoto As String = "@SettingsUploadPhoto"
        ReadOnly Property P_SettingsUploadPdf As String = "@SettingsUploadPdf"
        ReadOnly Property P_SettingsMinPasswordLength As String = "@SettingsMinPasswordLength"
        ReadOnly Property P_SettingsStorageProvider As String = "@SettingsStorageProvider"
        ReadOnly Property P_SettingsApiKey As String = "@SettingsApiKey"
        ReadOnly Property P_SettingsApiSecret As String = "@SettingsApiSecret"
        ReadOnly Property P_SettingsApiServiceUrl As String = "@SettingsApiServiceUrl"
        ReadOnly Property P_SettingsStorageDb As String = "@SettingsStorageDb"
        ReadOnly Property P_SettingsClient As String = "@SettingsClient"
    End Class
End Namespace
