# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net.

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@1
  displayName: 'Nuget Install'
  inputs:
    versionSpec: 
    checkLatest: true

- task: CmdLine@2
  displayName: 'Pre-Build Check - $(Build.SourcesDirectory) Alpha'
  inputs:
    script: |
      echo "File List - Ingrid-CI-Build"
      
      cd $(Build.SourcesDirectory)
      dir /b /s /A-D /o:gn

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: './Apps/Core/Vb/NuGet.config'
    externalFeedCredentials: 'ingrid'

- task: update-build-pipeline-variable@0
  displayName: 'Updating Variable'
  inputs:
    variableName: '$(var_g_Ingridversion_revision)'
    variableDataType: 'int'
    newVariableValueInInt: 1
    pipelineUpdateComment: '[AutoUpdate] : Update Pipeline Variable Task'
    usePAT: true
    patValue: '$(VAR_G_TOKEN_AZURE)'

- task: ReplaceInFilesTextByText@2
  displayName: 'Replacing: V_BRIDGEKEY.SALT'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: '= V_BRIDGE_KEY.SALT()'
    parameterReplaceText: '= "$(var_g_Salt)"'
    parameterTypeOfSearch: 'filesSearchPattern'

- task: ReplaceInFilesTextByText@2
  displayName: 'Replacing: V_BRIDGEKEY.SYNCFUSION'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: '= V_BRIDGE_KEY.SYNCFUSION()'
    parameterReplaceText: '= "$(var_g_SyncfusionKey)"'
    parameterTypeOfSearch: 'filesSearchPattern'

- task: ReplaceInFilesTextByText@2
  displayName: 'Replacing: V_BRIDGEKEY.BETTERSTACK_LOG'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'sourceToken: KEYLOG.BETTERSTACK_LOG()'
    parameterReplaceText: 'sourceToken: "$(var_g_BetterStack_Log)"'
    parameterTypeOfSearch: 'filesSearchPattern'

- task: ReplaceInFilesTextByText@2
  displayName: 'Replacing: {VERSION_MAJOR}'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'My.Application.Info.Version.Major'
    parameterReplaceText: '$(var_g_Ingridversion_major)'
    parameterTypeOfSearch: 'filesSearchPattern'

- task: ReplaceInFilesTextByText@2
  displayName: 'Replacing: {VERSION_MINOR}'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'My.Application.Info.Version.Minor'
    parameterReplaceText: '$(var_g_Ingridversion_minor)'
    parameterTypeOfSearch: 'filesSearchPattern'

- task: ReplaceInFilesTextByText@2
  displayName: 'Replacing: {VERSION_BUILD}'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'My.Application.Info.Version.Build'
    parameterReplaceText: '$(var_g_Ingridversion_build)'
    parameterTypeOfSearch: 'filesSearchPattern'

- task: ReplaceInFilesTextByText@2
  displayName: 'Replacing: {VERSION_REVISION}'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'My.Application.Info.Version.Revision'
    parameterReplaceText: '$(var_g_Ingridversion_revision)'
    parameterTypeOfSearch: 'filesSearchPattern'

- task: CmdLine@2
  displayName: 'Reviewing Codes'
  inputs:
    script: |
      echo "File List - Ingrid-CI-Build"
      
      cd $(Build.SourcesDirectory)
      dir /b /s /A-D /o:gn
      echo "---------------------------"
      echo "Reading CMC\Globals.vb"
      echo "---------------------------"
      more ".\Apps\Components\CMC\2090 - Module\Globals.vb"

- task: VSBuild@1
  displayName: 'VSBuild - CI'
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '/t:Publish /p:BootstrapperEnabled=True /p:IsWebBootstrapper=True /p:PublishProtocol=ClickOnce /p:Install=True /p:CreateDesktopShortcut=True /p:InstallFrom=Web /p:GenerateManifests=True /p:InstallUrl="https://www.iupdt.my.id/beta/" /p:PublishProfile="$(Build.SourcesDirectory)\Ingrid\Apps\Components\Ingrid-Launcher\My Project\PublishProfiles\ClickOnceProfile.pubxml" /p:PublishUrl="$(Build.SourcesDirectory)\Ingrid\Apps\Components\Ingrid-Launcher\bin\$(var_BuildConfiguration)\net7.0-windows\package\" /p:PublishDir="$(Build.SourcesDirectory)\Ingrid\Apps\Components\Ingrid-Launcher\bin\$(var_BuildConfiguration)\net7.0-windows\publish\" /p:ApplicationVersion="$(var_g_Ingridversion_major).$(var_g_Ingridversion_minor).$(var_g_Ingridversion_build).$(var_g_Ingridversion_revision)"'
    platform: 'any cpu'
    configuration: 'release'
    clean: true
    maximumCpuCount: true
    createLogFile: true