<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <OutputType>WinExe</OutputType>
    <StartupObject>Ingrid.My.MyApplication</StartupObject>
    <MyType>WindowsForms</MyType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <PrimaryVersionType>AssemblyVersionAttribute</PrimaryVersionType>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <AssemblyVersionSettings>
    </AssemblyVersionSettings>
    <AssemblyVersion>2.10.20167.1127</AssemblyVersion>
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
    <UpdatePackageVersion>False</UpdatePackageVersion>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
    <AssemblyFileVersionSettings>
    </AssemblyFileVersionSettings>
    <AssemblyInfoVersionSettings>
    </AssemblyInfoVersionSettings>
    <PublishUrl>D:\NO CLOUD\IPUDT\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>false</MapFileExtensions>
    <InstallUrl>http://www.iupdt.my.id/</InstallUrl>
    <SupportUrl>https://ardhagp.wordpress.com/contact-us/</SupportUrl>
    <ProductName>Ingrid</ProductName>
    <PublisherName>ArdhaGp</PublisherName>
    <SuiteName>Ingrid</SuiteName>
    <CreateWebPageOnPublish>true</CreateWebPageOnPublish>
    <WebPage>index.html</WebPage>
    <OpenBrowserOnPublish>false</OpenBrowserOnPublish>
    <ApplicationRevision>966</ApplicationRevision>
    <ApplicationVersion>2.10.20167.%2a</ApplicationVersion>
    <UseApplicationTrust>true</UseApplicationTrust>
    <CreateDesktopShortcut>true</CreateDesktopShortcut>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <BootstrapperComponentsUrl>\\lsb-pc-scm005\Shared Folder\000. INGRID SETUP\</BootstrapperComponentsUrl>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <UserSecretsId>f4e0ab0f-a60a-41b1-b56d-d9adae7b959d</UserSecretsId>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DocumentationFile>Ingrid.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <PropertyGroup />
  <PropertyGroup />
  <PropertyGroup>
    <ManifestCertificateThumbprint>61EC92E38B34468E1D5F319B8AE5666424C5E6D2</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>
    </ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>false</SignManifests>
  </PropertyGroup>
  <PropertyGroup>
    <TargetZone>Custom</TargetZone>
    <AssemblyTitle>Ingrid</AssemblyTitle>
    <Description>INGRID adalah sebuah aplikasi dengan berbagai macam fungsi, semacam ERP dengan flow yang disederhanakan.</Description>
    <Company>ArdhaGp</Company>
    <Product>Ingrid</Product>
    <Copyright>ArdhaGp©2023</Copyright>
    <FileVersion>2.10.20167.1127</FileVersion>
    <ImportedNamespaces>CMCv=False,Connect=False,LibSQL=False,Syncfusion=False,System.Drawing=False,System.Windows.Forms=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,Ingrid=True</ImportedNamespaces>
    <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>6.0</AnalysisLevel>
    <ApplicationIcon>Resources\ingrid_icon_2.ico</ApplicationIcon>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <OptionStrict>On</OptionStrict>
  </PropertyGroup>
  <ItemGroup>
    <Import Include="CMCv" />
    <Import Include="Connect" />
    <Import Include="LibSQL" />
    <Import Include="Syncfusion" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="030. Form\001. Mainframe\Splash.Designer.vb">
      <DependentUpon>Splash.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\010. System\010. Login\LOGIN.Designer.vb">
      <DependentUpon>LOGIN.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\010. System\020. Notification\NTFC.Designer.vb">
      <DependentUpon>NTFC.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\010. System\030. Connection Properties\CPDB.Designer.vb">
      <DependentUpon>CPDB.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\010. System\030. Connection Properties\frmConnectionProperties.Designer.vb">
      <DependentUpon>frmConnectionProperties.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MCTG - Material Catalog\MCTG_Editor.Designer.vb">
      <DependentUpon>MCTG_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMGR - Material Group\MMGR.Designer.vb">
      <DependentUpon>MMGR.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMGR - Material Group\MMGR_Editor.Designer.vb">
      <DependentUpon>MMGR_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMTY - Material Type\MMTY.Designer.vb">
      <DependentUpon>MMTY.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMTY - Material Type\MMTY_Editor.Designer.vb">
      <DependentUpon>MMTY_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMVT - Material Valuation\MMVT.Designer.vb">
      <DependentUpon>MMVT.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMVT - Material Valuation\MMVT_Editor.Designer.vb">
      <DependentUpon>MMVT_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MOW - Material Ownership\MOW.Designer.vb">
      <DependentUpon>MOW.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MOW - Material Ownership\MOW_Editor.Designer.vb">
      <DependentUpon>MOW_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MVTP - Movement Type\MVTP.Designer.vb">
      <DependentUpon>MVTP.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MVTP - Movement Type\MVTP_Editor.Designer.vb">
      <DependentUpon>MVTP_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\PLNT - Plant List\PLNT_Editor.Designer.vb">
      <DependentUpon>PLNT_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\SLOC - Storage Location\SLOC_Editor.Designer.vb">
      <DependentUpon>SLOC_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\UOM - Unit Of Measurement\UOM.Designer.vb">
      <DependentUpon>UOM.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\UOM - Unit Of Measurement\UOM_Editor.Designer.vb">
      <DependentUpon>UOM_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\03. Inventory\MMIT - Material Inventory Table\MMIT.Designer.vb">
      <DependentUpon>MMIT.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\03. Inventory\MMIT - Material Inventory Table\MMIT_Editor.Designer.vb">
      <DependentUpon>MMIT_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\03. Inventory\MMSI - Material Stock Info\MMSI.Designer.vb">
      <DependentUpon>MMSI.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\03. Inventory\MMSI - Material Stock Info\MMSI_Editor.Designer.vb">
      <DependentUpon>MMSI_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Additionals\MVT - Movement Type\MVT.Designer.vb">
      <DependentUpon>MVT.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Additionals\MVT - Movement Type\MVT_Editor.Designer.vb">
      <DependentUpon>MVT_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Additionals\STG - Direction List\STG.Designer.vb">
      <DependentUpon>STG.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Additionals\STG - Direction List\STG_Editor.Designer.vb">
      <DependentUpon>STG_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\DE001 - Logistics Data Entry\DE001.Designer.vb">
      <DependentUpon>DE001.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\DE001 - Logistics Data Entry\DE001_Editor.Designer.vb">
      <DependentUpon>DE001_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Tools\SYN01 - Import\SYN01.Designer.vb">
      <DependentUpon>SYN01.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Tools\SYN01 - Import\SYN01_Editor.Designer.vb">
      <DependentUpon>SYN01_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\01. Dashboard\frmACDashboard.Designer.vb">
      <DependentUpon>frmACDashboard.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\02. Master\ACBK - Accounting Book\ACBK.Designer.vb">
      <DependentUpon>ACBK.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\02. Master\ACBK - Accounting Book\ACBK_Editor.Designer.vb">
      <DependentUpon>ACBK_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\02. Master\ACGR - Account Group\ACGR.Designer.vb">
      <DependentUpon>ACGR.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\02. Master\ACGR - Account Group\ACGR_Editor.Designer.vb">
      <DependentUpon>ACGR_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\CCIN - Companies\CCIN_Editor.Designer.vb">
      <DependentUpon>CCIN_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\CDIN - Departements\CDIN_Editor.Designer.vb">
      <DependentUpon>CDIN_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\EPLS - Employee List\Addins\EPLS_Position.Designer.vb">
      <DependentUpon>EPLS_Position.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\EPLS - Employee List\EPLS_Editor.Designer.vb">
      <DependentUpon>EPLS_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\POST - Positions\POST.Designer.vb">
      <DependentUpon>POST.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\POST - Positions\POST_Editor.Designer.vb">
      <DependentUpon>POST_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Addins\DAR_SinglePDFViewer.Designer.vb">
      <DependentUpon>DAR_SinglePDFViewer.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Addins\DAR_SinglePhotoViewer.Designer.vb">
      <DependentUpon>DAR_SinglePhotoViewer.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\CCIN - Companies\CCIN.Designer.vb">
      <DependentUpon>CCIN.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\CDIN - Departements\CDIN.Designer.vb">
      <DependentUpon>CDIN.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\EPLS - Employee List\EPLS.Designer.vb">
      <DependentUpon>EPLS.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MCTG - Material Catalog\MCTG.Designer.vb">
      <DependentUpon>MCTG.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\DAR.Designer.vb">
      <DependentUpon>DAR.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\DAR_Editor.Designer.vb">
      <DependentUpon>DAR_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RPTFilter.Designer.vb">
      <DependentUpon>DAR_RPTFilter.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RPTContainer.Designer.vb">
      <DependentUpon>DAR_RPTContainer.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>DAR_RDS.xsd</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.vb">
      <DependentUpon>DAR_RDS.xsd</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DARD - DAR Dashboard\DARD.Designer.vb">
      <DependentUpon>DARD.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DRAA - DAR Area List\DRAA.Designer.vb">
      <DependentUpon>DRAA.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DRAA - DAR Area List\DRAA_Editor.Designer.vb">
      <DependentUpon>DRAA_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DRTM - DAR Templates\DRTM.Designer.vb">
      <DependentUpon>DRTM.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DRTM - DAR Templates\DRTM_Editor.Designer.vb">
      <DependentUpon>DRTM_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Archives\PEPR - Archived Custom Documents\PEPR.Designer.vb">
      <DependentUpon>PEPR.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Archives\PEPR - Archived Custom Documents\PEPR_Editor.Designer.vb">
      <DependentUpon>PEPR_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\REMS.Designer.vb">
      <DependentUpon>REMS.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\REMS_Editor.Designer.vb">
      <DependentUpon>REMS_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\REMS_Editor_Progress.Designer.vb">
      <DependentUpon>REMS_Editor_Progress.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\REMS_Editor_Switch.Designer.vb">
      <DependentUpon>REMS_Editor_Switch.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\MODS - Application Modules\MODS.Designer.vb">
      <DependentUpon>MODS.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\MODS - Application Modules\MODS_Editor.Designer.vb">
      <DependentUpon>MODS_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\MOGS - Modules Group\MOGS.Designer.vb">
      <DependentUpon>MOGS.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\SYSS - System Settings\SYSS.Designer.vb">
      <DependentUpon>SYSS.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\TXL - Templete List\TXL.Designer.vb">
      <DependentUpon>TXL.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\TXL - Templete List\TXL_Editor.Designer.vb">
      <DependentUpon>TXL_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\995. Etc\Dummy\Dummy.Designer.vb">
      <DependentUpon>Dummy.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\995. Etc\Dummy\Dummy_Editor.Designer.vb">
      <DependentUpon>Dummy_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\001. Credentials\UAC - User Access Credentials\Addins\UAC_Employee.Designer.vb">
      <DependentUpon>UAC_Employee.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\001. Credentials\UAC - User Access Credentials\UAC.Designer.vb">
      <DependentUpon>UAC.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\001. Credentials\UAC - User Access Credentials\UAC_Editor.Designer.vb">
      <DependentUpon>UAC_Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\995. Etc\Dummy\dummy_mainframe.Designer.vb">
      <DependentUpon>dummy_mainframe.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\030. Tools\010. Import Data\frmImports.Designer.vb">
      <DependentUpon>frmImports.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\PLNT - Plant List\PLNT.Designer.vb">
      <DependentUpon>PLNT.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\SLOC - Storage Location\SLOC.Designer.vb">
      <DependentUpon>SLOC.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\005. Procurement\02. Master\VDLS - Vendor List\VDLS.Designer.vb">
      <DependentUpon>VDLS.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\030. Tools\100. Communications\001. SAY - Chat Room\SAY.Designer.vb">
      <DependentUpon>SAY.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\030. Tools\999. First Guide\frmFistGuide.Designer.vb">
      <DependentUpon>frmFistGuide.vb</DependentUpon>
    </Compile>
    <Compile Update="902. Settings\General.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>General.settings</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RContent.rdlc" />
  </ItemGroup>
  <ItemGroup>
    <None Include="000. Programmer%27s Guide\All-In-One Code Framework Coding Standards.docx" />
    <None Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.xsc">
      <DependentUpon>DAR_RDS.xsd</DependentUpon>
    </None>
    <None Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.xsd">
      <SubType>Designer</SubType>
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DAR_RDS.Designer.vb</LastGenOutput>
    </None>
    <None Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.xss">
      <DependentUpon>DAR_RDS.xsd</DependentUpon>
    </None>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="My Project\Settings.settings">
      <CustomToolNamespace>My</CustomToolNamespace>
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
    <None Update="Resources\CATALOG.mdf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\catalog_log.ldf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\DEV_CATALOG.mdf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\dev_catalog_log.ldf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ERRLOG.mdf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\errlog_log.ldf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\mainframe_ms_start_Login.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\mainframe_ms_start_Logout.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\mainframe_ms_start_Exit.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="030. Form\010. System\090. Password Generator\" />
    <Folder Include="030. Form\020. Commands\001. Logistics\01. Dashboard\" />
    <Folder Include="030. Form\020. Commands\001. Logistics\04. Transaction\DE001 - Logistics Data Entry\Addins\" />
    <Folder Include="030. Form\020. Commands\002. Administration\01. Documents\" />
    <Folder Include="030. Form\020. Commands\003. Accounting\03. Transaction\ACTP - Transaction Posting\" />
    <Folder Include="030. Form\020. Commands\006. Transportation\01. Dashboard\" />
    <Folder Include="030. Form\020. Commands\006. Transportation\02. Master\VHCL - Vehicle List\" />
    <Folder Include="030. Form\020. Commands\006. Transportation\02. Master\VHCT - Vehicle Type\" />
    <Folder Include="030. Form\020. Commands\100. Personal Folder\PINF - Personal Information\" />
    <Folder Include="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\Addins\" />
    <Folder Include="030. Form\020. Commands\750. Custom\To Do List\REMC - To Do List Categories\" />
    <Folder Include="030. Form\020. Commands\800. System Settings\100. Application\MODS - Application Modules\Addins\" />
    <Folder Include="030. Form\020. Commands\800. System Settings\900. Files\" />
    <Folder Include="030. Form\020. Commands\990. Tools\" />
    <Folder Include="030. Form\030. Tools\000. Console\" />
    <Folder Include="090. Services\" />
    <Folder Include="901. Resource\Database\" />
    <Folder Include="901. Resource\Images\" />
    <Folder Include="x64\" />
    <Folder Include="x86\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\mainframe_ms_master_cabinet.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Plant_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Departement_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Employee_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Error_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Login_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Logout_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\TextEditor_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Plant_002_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Storage_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Catalogue_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Exports_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Imports_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Error_002_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Question_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\AccountGroup_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Information_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Alert_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\AccountingBook_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Error_002_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\Question_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\AccountGroup_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\Information_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\Alert_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\AccountingBook_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\DailyActivity_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\DAR_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\CALENDAR_001_512_icon.png" />
    <Content Include="Resources\app_settings.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\catalog.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\dev_catalog.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\errlog.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\ingrid_icon_2.ico" />
    <EmbeddedResource Include="Resources\COMPRESS_001_512_icon_.png" />
    <EmbeddedResource Include="Resources\Connected.ico" />
    <EmbeddedResource Include="Resources\CONN_.png" />
    <EmbeddedResource Include="Resources\SETTINGS_001_512_icon.png" />
    <EmbeddedResource Include="Resources\TIMELINE_001_512_icon.png" />
    <EmbeddedResource Include="Resources\PRINTER_001_512_icon.png" />
    <EmbeddedResource Include="Resources\DAR_003_512_icon.png" />
    <EmbeddedResource Include="Resources\SEARCH_001_512_icon.png" />
    <EmbeddedResource Include="Resources\DUMMY_001_512_icon.png" />
    <EmbeddedResource Include="Resources\ACBK_001_512_icon.png" />
    <EmbeddedResource Include="Resources\ACGR_001_512_icon.png" />
    <EmbeddedResource Include="Resources\DAR_002_512_icon.png" />
    <EmbeddedResource Include="Resources\CCIN_002_512_icon.png" />
    <EmbeddedResource Include="Resources\CDIN_001_512_icon.png" />
    <EmbeddedResource Include="Resources\GO_001_512_icon.png" />
    <EmbeddedResource Include="Resources\FEMALE_001_512_icon.png" />
    <EmbeddedResource Include="Resources\MALE_001_512_icon.png" />
    <EmbeddedResource Include="Resources\EPLS_001_512_icon.png" />
    <EmbeddedResource Include="Resources\CCIN_001_512_icon.png" />
    <EmbeddedResource Include="Resources\EDIT_002_512_icon .png" />
    <EmbeddedResource Include="Resources\PCTPRV_001_512_icon.png" />
    <EmbeddedResource Include="Resources\PDFPRV_001_512_icon.png" />
    <EmbeddedResource Include="Resources\UAC_001_512_icon.png" />
    <EmbeddedResource Include="Resources\MODS_001_512_icon.png" />
    <EmbeddedResource Include="Resources\LOGIN_001_512_icon.png" />
    <EmbeddedResource Include="Resources\DAR_001_512_icon.png" />
    <EmbeddedResource Include="Resources\inggrid_icon-1.ico" />
    <EmbeddedResource Include="Resources\Notification_001_16_FFF00000_.png" />
    <EmbeddedResource Include="Resources\Notification_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Notification_001_16_FFFFF000_.png" />
    <EmbeddedResource Include="Resources\Like_002_16_#FFFC0000_.png" />
    <EmbeddedResource Include="Resources\Like_001_16_#FFFC0000_.png" />
    <EmbeddedResource Include="Resources\SaveAs_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Copy_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Peek_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Photo_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Plus_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Bullets_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\In-Grid.png" />
    <EmbeddedResource Include="Resources\StartUp.jpg" />
    <EmbeddedResource Include="Resources\Application_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\UAC_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Components\Bridge\Bridge.csproj" />
    <ProjectReference Include="..\..\Components\CMC\CMCv.vbproj" />
    <ProjectReference Include="..\..\Components\Connect\Connect.vbproj" />
    <ProjectReference Include="..\..\Components\LibSQL\LibSQL.vbproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.13.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Syncfusion.Grid.Windows" Version="23.1.41" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="23.1.41" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="23.1.41" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Management" Version="10.0.0" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="030. Form\001. Mainframe\Mainframe_nf_4.8.Designer.vb" />
    <Compile Remove="030. Form\001. Mainframe\Mainframe_nf_4.8.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\CCTG - Catalog\frmCatalog.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\CCTG - Catalog\frmCatalog.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMGR - Material Group\frmMaterialGroup.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMGR - Material Group\frmMaterialGroup.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMTY - Material Type\frmMaterialType.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMTY - Material Type\frmMaterialType.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\frmStorage.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\frmStorage.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\PLNT - Plant\frmPlant.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\PLNT - Plant\frmPlant.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Dashboard\frmACDashboard.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Dashboard\frmACDashboard.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook_Editor.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook_Editor.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup_Editor.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup_Editor.vb" />
    <EmbeddedResource Remove="030. Form\001. Mainframe\Mainframe_nf_4.8.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\CCTG - Catalog\frmCatalog.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMGR - Material Group\frmMaterialGroup.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMTY - Material Type\frmMaterialType.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\frmStorage.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\PLNT - Plant\frmPlant.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Dashboard\frmACDashboard.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook_Editor.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup_Editor.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\app_settings.db" />
    <None Remove="Resources\catalog.db" />
    <None Remove="Resources\dev_catalog.db" />
    <None Remove="Resources\errlog.db" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <Generator>PublicVbMyResourcesResXFileCodeGenerator</Generator>
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>