<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <OutputType>Library</OutputType>
    <StartupObject>Ingrid.My.MyApplication</StartupObject>
    <MyType>WindowsForms</MyType>
    <LangVersion>latest</LangVersion>
    <VBOptionStrict>On</VBOptionStrict>
    <VBOptionExplicit>On</VBOptionExplicit>
    <VBOptionInfer>Off</VBOptionInfer>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <PrimaryVersionType>AssemblyVersionAttribute</PrimaryVersionType>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <AssemblyVersionSettings>
    </AssemblyVersionSettings>
    <AssemblyVersion>2.10.20167.1127</AssemblyVersion>
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
    <UpdatePackageVersion>False</UpdatePackageVersion>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
    <AssemblyFileVersionSettings>
    </AssemblyFileVersionSettings>
    <AssemblyInfoVersionSettings>
    </AssemblyInfoVersionSettings>
    <PublishUrl>D:\NO CLOUD\IPUDT\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>false</MapFileExtensions>
    <InstallUrl>http://www.iupdt.my.id/</InstallUrl>
    <SupportUrl>https://ardhagp.wordpress.com/contact-us/</SupportUrl>
    <ProductName>Ingrid</ProductName>
    <PublisherName>ArdhaGp</PublisherName>
    <SuiteName>Ingrid</SuiteName>
    <CreateWebPageOnPublish>true</CreateWebPageOnPublish>
    <WebPage>index.html</WebPage>
    <OpenBrowserOnPublish>false</OpenBrowserOnPublish>
    <ApplicationRevision>966</ApplicationRevision>
    <ApplicationVersion>2.10.20167.%2a</ApplicationVersion>
    <UseApplicationTrust>true</UseApplicationTrust>
    <CreateDesktopShortcut>true</CreateDesktopShortcut>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <BootstrapperComponentsUrl>\\lsb-pc-scm005\Shared Folder\000. INGRID SETUP\</BootstrapperComponentsUrl>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <UserSecretsId>f4e0ab0f-a60a-41b1-b56d-d9adae7b959d</UserSecretsId>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DocumentationFile>Ingrid.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <PropertyGroup />
  <PropertyGroup />
  <PropertyGroup>
    <ManifestCertificateThumbprint>61EC92E38B34468E1D5F319B8AE5666424C5E6D2</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>
    </ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>false</SignManifests>
  </PropertyGroup>
  <PropertyGroup>
    <TargetZone>Custom</TargetZone>
    <AssemblyTitle>Ingrid</AssemblyTitle>
    <Description>INGRID adalah sebuah aplikasi dengan berbagai macam fungsi, semacam ERP dengan flow yang disederhanakan.</Description>
    <Company>ArdhaGp</Company>
    <Product>Ingrid</Product>
    <Copyright>ArdhaGp©2026</Copyright>
    <FileVersion>2.10.20167.1127</FileVersion>
    <ImportedNamespaces>CMCv=False,Connect=False,LibSQL=False,Syncfusion=False,System.Drawing=False,System.Windows.Forms=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,Ingrid=True</ImportedNamespaces>
    <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>6.0</AnalysisLevel>
    <ApplicationIcon>Resources\ingrid_icon_2.ico</ApplicationIcon>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <OptionStrict>On</OptionStrict>
    <AssemblyName>Ingrid.Core</AssemblyName>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="000. Programmer%27s Guide\**" />
    <Compile Remove="030. Form\020. Commands\002. Administration\**" />
    <Compile Remove="030. Form\020. Commands\006. Transportation\**" />
    <Compile Remove="030. Form\020. Commands\100. Personal Folder\**" />
    <Compile Remove="030. Form\020. Commands\990. Tools\**" />
    <Compile Remove="090. Services\**" />
    <Compile Remove="UI\Database\**" />
    <Compile Remove="x64\**" />
    <Compile Remove="x86\**" />
    <EmbeddedResource Remove="000. Programmer%27s Guide\**" />
    <EmbeddedResource Remove="030. Form\020. Commands\002. Administration\**" />
    <EmbeddedResource Remove="030. Form\020. Commands\006. Transportation\**" />
    <EmbeddedResource Remove="030. Form\020. Commands\100. Personal Folder\**" />
    <EmbeddedResource Remove="030. Form\020. Commands\990. Tools\**" />
    <EmbeddedResource Remove="090. Services\**" />
    <EmbeddedResource Remove="UI\Database\**" />
    <EmbeddedResource Remove="x64\**" />
    <EmbeddedResource Remove="x86\**" />
    <None Remove="000. Programmer%27s Guide\**" />
    <None Remove="030. Form\020. Commands\002. Administration\**" />
    <None Remove="030. Form\020. Commands\006. Transportation\**" />
    <None Remove="030. Form\020. Commands\100. Personal Folder\**" />
    <None Remove="030. Form\020. Commands\990. Tools\**" />
    <None Remove="090. Services\**" />
    <None Remove="UI\Database\**" />
    <None Remove="x64\**" />
    <None Remove="x86\**" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="CMCv" />
    <Import Include="Connect" />
    <Import Include="LibSQL" />
    <Import Include="Syncfusion" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="030. Form\001. Mainframe\FRMsplash.Designer.vb">
      <DependentUpon>FRMsplash.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\010. System\010. Login\FRMlogin.Designer.vb">
      <DependentUpon>FRMlogin.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\010. System\020. Notification\FRMntfc.Designer.vb">
      <DependentUpon>FRMntfc.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\010. System\030. Connection Properties\FRMcpdb.Designer.vb">
      <DependentUpon>FRMcpdb.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\010. System\030. Connection Properties\FRMconn.Designer.vb">
      <DependentUpon>FRMconn.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MCTG - Material Catalog\FRMmctgEditor.Designer.vb">
      <DependentUpon>FRMmctgEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMGR - Material Group\FRMmmgr.Designer.vb">
      <DependentUpon>FRMmmgr.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMGR - Material Group\FRMmmgrEditor.Designer.vb">
      <DependentUpon>FRMmmgrEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMTY - Material Type\FRMmmty.Designer.vb">
      <DependentUpon>FRMmmty.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMTY - Material Type\FRMmmtyEditor.Designer.vb">
      <DependentUpon>FRMmmtyEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMVT - Material Valuation\FRMmmvt.Designer.vb">
      <DependentUpon>FRMmmvt.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MMVT - Material Valuation\FRMmmvtEditor.Designer.vb">
      <DependentUpon>FRMmmvtEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MOW - Material Ownership\FRMmow.Designer.vb">
      <DependentUpon>FRMmow.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MOW - Material Ownership\FRMmowEditor.Designer.vb">
      <DependentUpon>FRMmowEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MVTP - Movement Type\FRMmvtp.Designer.vb">
      <DependentUpon>FRMmvtp.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MVTP - Movement Type\FRMmvtpEditor.Designer.vb">
      <DependentUpon>FRMmvtpEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\PLNT - Plant List\FRMplntEditor.Designer.vb">
      <DependentUpon>FRMplntEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\SLOC - Storage Location\FRMslocEditor.Designer.vb">
      <DependentUpon>FRMslocEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\UOM - Unit Of Measurement\FRMuom.Designer.vb">
      <DependentUpon>FRMuom.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\UOM - Unit Of Measurement\FRMuomEditor.Designer.vb">
      <DependentUpon>FRMuomEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\03. Inventory\MMIT - Material Inventory Table\FRMmmit.Designer.vb">
      <DependentUpon>FRMmmit.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\03. Inventory\MMIT - Material Inventory Table\FRMmmitEditor.Designer.vb">
      <DependentUpon>FRMmmitEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\03. Inventory\MMSI - Material Stock Info\FRMmmsi.Designer.vb">
      <DependentUpon>FRMmmsi.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\03. Inventory\MMSI - Material Stock Info\FRMmmsiEditor.Designer.vb">
      <DependentUpon>FRMmmsiEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Additionals\MVT - Movement Type\FRMmvt.Designer.vb">
      <DependentUpon>FRMmvt.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Additionals\MVT - Movement Type\FRMmvtEditor.Designer.vb">
      <DependentUpon>FRMmvtEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Additionals\STG - Direction List\FRMstg.Designer.vb">
      <DependentUpon>FRMstg.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Additionals\STG - Direction List\FRMstgEditor.Designer.vb">
      <DependentUpon>FRMstgEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\DE001 - Logistics Data Entry\FRMde001.Designer.vb">
      <DependentUpon>FRMde001.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\DE001 - Logistics Data Entry\FRMde001Editor.Designer.vb">
      <DependentUpon>FRMde001Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Tools\SYN01 - Import\FRMsyn01.Designer.vb">
      <DependentUpon>FRMsyn01.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\04. Transaction\Tools\SYN01 - Import\FRMsyn01Editor.Designer.vb">
      <DependentUpon>FRMsyn01Editor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\01. Dashboard\FRMaccountingDashboard.Designer.vb">
      <DependentUpon>FRMaccountingDashboard.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\02. Master\ACBK - Accounting Book\FRMacbk.Designer.vb">
      <DependentUpon>FRMacbk.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\02. Master\ACBK - Accounting Book\FRMacbkEditor.Designer.vb">
      <DependentUpon>FRMacbkEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\02. Master\ACGR - Account Group\FRMacgr.Designer.vb">
      <DependentUpon>FRMacgr.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\003. Accounting\02. Master\ACGR - Account Group\FRMacgrEditor.Designer.vb">
      <DependentUpon>FRMacgrEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\CCIN - Companies\FRMccinEditor.Designer.vb">
      <DependentUpon>FRMccinEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\CDIN - Departements\FRMcdinEditor.Designer.vb">
      <DependentUpon>FRMcdinEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\EPLS - Employee List\Addins\FRMeplsPosition - Copy.Designer.vb">
      <DependentUpon>FRMeplsPosition.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\EPLS - Employee List\Addins\FRMeplsEmploymentType.vb" />
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\EPLS - Employee List\Addins\FRMeplsPosition.Designer.vb">
      <DependentUpon>FRMeplsPosition.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\EPLS - Employee List\FRMeplsEditor.Designer.vb">
      <DependentUpon>FRMeplsEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\POST - Positions\FRMpost.Designer.vb">
      <DependentUpon>FRMpost.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\POST - Positions\FRMpostEditor.Designer.vb">
      <DependentUpon>FRMpostEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Addins\FRMaddinsDARsinglePDFViewer.Designer.vb">
      <DependentUpon>FRMaddinsDARsinglePdfViewer.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Addins\FRMaddinsDARsinglePhotoViewer.Designer.vb">
      <DependentUpon>FRMaddinsDARsinglePhotoViewer.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\CCIN - Companies\FRMccin.Designer.vb">
      <DependentUpon>FRMccin.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\CDIN - Departements\FRMcdin.Designer.vb">
      <DependentUpon>FRMcdin.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\004. Management\02. Master\EPLS - Employee List\FRMepls.Designer.vb">
      <DependentUpon>FRMepls.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\MCTG - Material Catalog\FRMmctg.Designer.vb">
      <DependentUpon>FRMmctg.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\FRMdar.Designer.vb">
      <DependentUpon>FRMdar.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\FRMdarEditor.Designer.vb">
      <DependentUpon>FRMdarEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\FRMreportsDARfilter.Designer.vb">
      <DependentUpon>FRMreportsDARfilter.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\FRMreportsDARcontainer.Designer.vb">
      <DependentUpon>FRMreportsDARcontainer.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>DAR_RDS.xsd</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.vb">
      <DependentUpon>DAR_RDS.xsd</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DARD - DAR Dashboard\FRMdard.Designer.vb">
      <DependentUpon>FRMdard.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DRAA - DAR Area List\FRMdraa.Designer.vb">
      <DependentUpon>FRMdraa.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DRAA - DAR Area List\FRMdraaEditor.Designer.vb">
      <DependentUpon>FRMdraaEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DRTM - DAR Templates\FRMdrtm.Designer.vb">
      <DependentUpon>FRMdrtm.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Activity Reports\DRTM - DAR Templates\FRMdrtmEditor.Designer.vb">
      <DependentUpon>FRMdrtmEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Archives\PEPR - Archived Custom Documents\FRMpepr.Designer.vb">
      <DependentUpon>FRMpepr.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\Archives\PEPR - Archived Custom Documents\FRMpeprEditor.Designer.vb">
      <DependentUpon>FRMpeprEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\FRMrems.Designer.vb">
      <DependentUpon>FRMrems.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\FRMremsEditor.Designer.vb">
      <DependentUpon>FRMremsEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\FRMremsEditorProgress.Designer.vb">
      <DependentUpon>FRMremsEditorProgress.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\FRMremsEditorSwitch.Designer.vb">
      <DependentUpon>FRMremsEditorSwitch.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\MODS - Application Modules\FRMmods.Designer.vb">
      <DependentUpon>FRMmods.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\MODS - Application Modules\FRMmodsEditor.Designer.vb">
      <DependentUpon>FRMmodsEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\MOGS - Modules Group\FRMmogs.Designer.vb">
      <DependentUpon>FRMmogs.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\SYSS - System Settings\FRMsyss.Designer.vb">
      <DependentUpon>FRMsyss.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\TXL - Templete List\FRMtxl.Designer.vb">
      <DependentUpon>FRMtxl.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\100. Application\TXL - Templete List\FRMtxlEditor.Designer.vb">
      <DependentUpon>FRMtxlEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\995. Etc\Dummy\FRMdummy.Designer.vb">
      <DependentUpon>FRMdummy.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\995. Etc\Dummy\FRMdummyEditor.Designer.vb">
      <DependentUpon>FRMdummyEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\001. Credentials\UAC - User Access Credentials\Addins\FRMuacEmployee.Designer.vb">
      <DependentUpon>FRMuacEmployee.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\001. Credentials\UAC - User Access Credentials\FRMuac.Designer.vb">
      <DependentUpon>FRMuac.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\800. System Settings\001. Credentials\UAC - User Access Credentials\FRMuacEditor.Designer.vb">
      <DependentUpon>FRMuacEditor.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\995. Etc\Dummy\FRMdummyMainframe.Designer.vb">
      <DependentUpon>FRMdummyMainframe.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\030. Tools\010. Import Data\frmImports.Designer.vb">
      <DependentUpon>FRMimports.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\PLNT - Plant List\FRMplnt.Designer.vb">
      <DependentUpon>FRMplnt.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\001. Logistics\02. Master\SLOC - Storage Location\FRMsloc.Designer.vb">
      <DependentUpon>FRMsloc.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\020. Commands\005. Procurement\02. Master\VDLS - Vendor List\FRMvdls.Designer.vb">
      <DependentUpon>FRMvdls.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\030. Tools\100. Communications\001. SAY - Chat Room\FRMsay.Designer.vb">
      <DependentUpon>FRMsay.vb</DependentUpon>
    </Compile>
    <Compile Update="030. Form\030. Tools\999. First Guide\FRMfirstguide.Designer.vb">
      <DependentUpon>FRMfirstguide.vb</DependentUpon>
    </Compile>
    <Compile Update="UI\Dataset\ADSglobal.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ADSglobal.xsd</DependentUpon>
    </Compile>
    <Compile Update="902. Settings\General.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>General.settings</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RContent.rdlc" />
  </ItemGroup>
  <ItemGroup>
    <None Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.xsc">
      <DependentUpon>DAR_RDS.xsd</DependentUpon>
    </None>
    <None Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.xsd">
      <SubType>Designer</SubType>
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DAR_RDS.Designer.vb</LastGenOutput>
    </None>
    <None Update="030. Form\020. Commands\750. Custom\Activity Reports\DAR - Daily Activity Reports\Reports\DAR_RDS.xss">
      <DependentUpon>DAR_RDS.xsd</DependentUpon>
    </None>
    <None Update="902. Settings\General.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
    </None>
    <None Update="UI\Dataset\ADSglobal.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>ADSglobal.Designer.vb</LastGenOutput>
    </None>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="My Project\Settings.settings">
      <CustomToolNamespace>My</CustomToolNamespace>
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\mainframe_ms_start_Login.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\mainframe_ms_start_Logout.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\mainframe_ms_start_Exit.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="030. Form\010. System\090. Password Generator\" />
    <Folder Include="030. Form\020. Commands\001. Logistics\01. Dashboard\" />
    <Folder Include="030. Form\020. Commands\001. Logistics\04. Transaction\DE001 - Logistics Data Entry\Addins\" />
    <Folder Include="030. Form\020. Commands\003. Accounting\03. Transaction\ACTP - Transaction Posting\" />
    <Folder Include="030. Form\020. Commands\750. Custom\To Do List\REM - To Do List\Addins\" />
    <Folder Include="030. Form\020. Commands\750. Custom\To Do List\REMC - To Do List Categories\" />
    <Folder Include="030. Form\020. Commands\800. System Settings\100. Application\MODS - Application Modules\Addins\" />
    <Folder Include="030. Form\020. Commands\800. System Settings\900. Files\" />
    <Folder Include="030. Form\030. Tools\000. Console\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\mainframe_ms_master_cabinet.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Plant_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Departement_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Employee_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Error_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Login_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Logout_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\TextEditor_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Plant_002_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Storage_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Catalogue_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Exports_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Imports_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Error_002_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Question_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\AccountGroup_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Information_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Alert_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\AccountingBook_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Error_002_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\Question_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\AccountGroup_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\Information_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\Alert_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\AccountingBook_001_90_FFFFFFFF.png" />
    <EmbeddedResource Include="Resources\DailyActivity_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\DAR_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\CALENDAR_001_512_icon.png" />
    <Content Include="Resources\app_settings.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\catalog.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\ingrid_icon_2.ico" />
    <EmbeddedResource Include="Resources\COMPRESS_001_512_icon_.png" />
    <EmbeddedResource Include="Resources\Connected.ico" />
    <EmbeddedResource Include="Resources\CONN_.png" />
    <EmbeddedResource Include="Resources\SETTINGS_001_512_icon.png" />
    <EmbeddedResource Include="Resources\TIMELINE_001_512_icon.png" />
    <EmbeddedResource Include="Resources\PRINTER_001_512_icon.png" />
    <EmbeddedResource Include="Resources\DAR_003_512_icon.png" />
    <EmbeddedResource Include="Resources\SEARCH_001_512_icon.png" />
    <EmbeddedResource Include="Resources\DUMMY_001_512_icon.png" />
    <EmbeddedResource Include="Resources\ACBK_001_512_icon.png" />
    <EmbeddedResource Include="Resources\ACGR_001_512_icon.png" />
    <EmbeddedResource Include="Resources\DAR_002_512_icon.png" />
    <EmbeddedResource Include="Resources\CCIN_002_512_icon.png" />
    <EmbeddedResource Include="Resources\CDIN_001_512_icon.png" />
    <EmbeddedResource Include="Resources\GO_001_512_icon.png" />
    <EmbeddedResource Include="Resources\FEMALE_001_512_icon.png" />
    <EmbeddedResource Include="Resources\MALE_001_512_icon.png" />
    <EmbeddedResource Include="Resources\EPLS_001_512_icon.png" />
    <EmbeddedResource Include="Resources\CCIN_001_512_icon.png" />
    <EmbeddedResource Include="Resources\EDIT_002_512_icon .png" />
    <EmbeddedResource Include="Resources\PCTPRV_001_512_icon.png" />
    <EmbeddedResource Include="Resources\PDFPRV_001_512_icon.png" />
    <EmbeddedResource Include="Resources\UAC_001_512_icon.png" />
    <EmbeddedResource Include="Resources\MODS_001_512_icon.png" />
    <EmbeddedResource Include="Resources\LOGIN_001_512_icon.png" />
    <EmbeddedResource Include="Resources\DAR_001_512_icon.png" />
    <EmbeddedResource Include="Resources\inggrid_icon-1.ico" />
    <EmbeddedResource Include="Resources\Notification_001_16_FFF00000_.png" />
    <EmbeddedResource Include="Resources\Notification_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Notification_001_16_FFFFF000_.png" />
    <EmbeddedResource Include="Resources\Like_002_16_#FFFC0000_.png" />
    <EmbeddedResource Include="Resources\Like_001_16_#FFFC0000_.png" />
    <EmbeddedResource Include="Resources\SaveAs_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Copy_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Peek_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Photo_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Plus_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Bullets_001_16_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\In-Grid.png" />
    <EmbeddedResource Include="Resources\StartUp.jpg" />
    <EmbeddedResource Include="Resources\Application_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\UAC_001_90_FFFFFFFF_.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Components\Bridge\Bridge.csproj" />
    <ProjectReference Include="..\..\Components\CMC\CMCv.vbproj" />
    <ProjectReference Include="..\..\Components\Connect\Connect.vbproj" />
    <ProjectReference Include="..\..\Components\LibAPI\LibAPI.vbproj" />
    <ProjectReference Include="..\..\Components\LibSQL\LibSQL.vbproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.100.2" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Syncfusion.Grid.Windows" Version="33.2.15" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="33.2.15" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="33.2.15" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.9" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Management" Version="10.0.9" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="030. Form\001. Mainframe\Mainframe_nf_4.8.Designer.vb" />
    <Compile Remove="030. Form\001. Mainframe\Mainframe_nf_4.8.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\CCTG - Catalog\frmCatalog.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\CCTG - Catalog\frmCatalog.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMGR - Material Group\frmMaterialGroup.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMGR - Material Group\frmMaterialGroup.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMTY - Material Type\frmMaterialType.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMTY - Material Type\frmMaterialType.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\frmStorage.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\frmStorage.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\PLNT - Plant\frmPlant.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\PLNT - Plant\frmPlant.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Dashboard\frmACDashboard.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Dashboard\frmACDashboard.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook_Editor.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook_Editor.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup_Editor.Designer.vb" />
    <Compile Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup_Editor.vb" />
    <EmbeddedResource Remove="030. Form\001. Mainframe\Mainframe_nf_4.8.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\CCTG - Catalog\frmCatalog.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMGR - Material Group\frmMaterialGroup.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\01. Material Master Data\MMTY - Material Type\frmMaterialType.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\frmStorage.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\001. Logistics\04. Plant and Storage\PLNT - Plant\frmPlant.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Dashboard\frmACDashboard.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Master\ACBK - Accounting Book\frmAccountingBook_Editor.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup.resx" />
    <EmbeddedResource Remove="030. Form\020. Commands\003. Accounting\Master\ACGR - Account Group\frmAccountGroup_Editor.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\app_settings.db" />
    <None Remove="Resources\catalog.db" />
    <None Remove="Resources\CATALOG.mdb" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <Generator>PublicVbMyResourcesResXFileCodeGenerator</Generator>
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>