'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ingrid.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ACBK_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACBK_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AccountGroup_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccountGroup_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AccountingBook_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AccountingBook_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ACGR_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACGR_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ADD_001_16_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADD_001_16_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ALERT_001_256_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ALERT_001_256_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ALERT_001_512_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ALERT_001_512_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Alert_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alert_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property app_settings() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("app_settings", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Application_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Application_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BROWSE_001_16_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BROWSE_001_16_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Bullets_001_16_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bullets_001_16_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CALENDAR_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CALENDAR_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Catalogue_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Catalogue_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CCIN_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCIN_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CCIN_002_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCIN_002_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CCIN_003_512_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCIN_003_512_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CDIN_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CDIN_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CDIN_002_512_ICO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CDIN_002_512_ICO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CDIN_003_512_ICO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CDIN_003_512_ICO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property COMPRESS_001_512_icon_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COMPRESS_001_512_icon_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CONN_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CONN_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property Connected() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Connected", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Copy_001_16_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy_001_16_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property COPY_001_16_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COPY_001_16_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DailyActivity_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DailyActivity_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DAR_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DAR_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DAR_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DAR_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DAR_002_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DAR_002_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DAR_003_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DAR_003_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Departement_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Departement_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DOWNLOAD_001_16_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOWNLOAD_001_16_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DUMMY_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DUMMY_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property EDIT_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDIT_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Employee_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Employee_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property EPLS_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EPLS_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ERROR_001_256_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ERROR_001_256_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ERROR_001_512_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ERROR_001_512_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Error_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Error_002_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_002_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Exports_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exports_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FEMALE_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FEMALE_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FOLDER_001_16_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FOLDER_001_16_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_box_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_box_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_crisismanagement_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_crisismanagement_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_deliverytruck_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_deliverytruck_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_documents_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_documents_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_dollar_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_dollar_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_folder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_folder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_id_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_id_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_idcard_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_idcard_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_menu_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_menu_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_performace_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_performace_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_playbutton_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_playbutton_512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_puzzle_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_puzzle_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_record_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_record_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_settings_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_settings_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_settings2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_settings2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property for_treeview_shoppingcart_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("for_treeview_shoppingcart_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property GO_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GO_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Imports_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Imports_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property In_Grid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("In_Grid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property INFORMATION_001_256_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INFORMATION_001_256_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Information_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property inggrid_icon_1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("inggrid_icon_1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property ingrid_icon_2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ingrid_icon_2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Like_001_16__FFFC0000_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Like_001_16__FFFC0000_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LIKE_001_16_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LIKE_001_16_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Like_002_16__FFFC0000_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Like_002_16__FFFC0000_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LOGIN_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Login_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Logout_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logout_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mainframe_ms_master_cabinet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainframe_ms_master_cabinet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mainframe_ms_start_Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainframe_ms_start_Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mainframe_ms_start_Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainframe_ms_start_Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mainframe_ms_start_Logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainframe_ms_start_Logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MALE_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MALE_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MDI_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MDI_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MDI_Background_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MDI_Background_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MODS_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MODS_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Notification_001_16_FFF00000_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notification_001_16_FFF00000_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Notification_001_16_FFFFF000_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notification_001_16_FFFFF000_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Notification_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notification_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PCTPRV_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PCTPRV_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PDFPRV_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PDFPRV_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Peek_001_16_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Peek_001_16_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Peek_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Peek_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Photo_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Photo_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Plant_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Plant_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Plant_002_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Plant_002_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Plus_001_16_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Plus_001_16_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property POST_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("POST_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property POST_002_512_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("POST_002_512_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PRINTER_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRINTER_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property QUESTION_001_256_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QUESTION_001_256_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Question_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property RESET_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RESET_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SaveAs_001_16_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAs_001_16_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SEARCH_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SEARCH_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SETTINGS_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SHARE_001_16_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SHARE_001_16_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property StartUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Storage_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Storage_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TextEditor_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextEditor_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TIMELINE_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TIMELINE_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property UAC_001_512_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UAC_001_512_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property UAC_001_90_FFFFFFFF_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UAC_001_90_FFFFFFFF_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property UAC_002_512_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UAC_002_512_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ZOOMNORMAL_001_16_ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZOOMNORMAL_001_16_ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
