<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Library</OutputType>
    <MyType>WindowsForms</MyType>
    <LangVersion>latest</LangVersion>
    <VBOptionStrict>On</VBOptionStrict>
    <VBOptionExplicit>On</VBOptionExplicit>
    <VBOptionInfer>Off</VBOptionInfer>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <PrimaryVersionType>AssemblyVersionAttribute</PrimaryVersionType>
    <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
    <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
    <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
    <AssemblyInfoVersionSettings>
    </AssemblyInfoVersionSettings>
    <ShouldCreateLogs>True</ShouldCreateLogs>
    <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UpdatePackageVersion>False</UpdatePackageVersion>
    <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
    <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
    <AssemblyVersion>2.10.20167.1127</AssemblyVersion>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <UserSecretsId>6a79fad4-b2d4-4093-8fa0-744b9ed27bb8</UserSecretsId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DocumentationFile>CMCv.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <CodeAnalysisLogFile>bin\Release\Mainframe_n_6.dll.CodeAnalysisLog.xml</CodeAnalysisLogFile>
    <CodeAnalysisRuleSet>..\..\..\..\..\..\..\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Static Analysis Tools\Rule Sets\MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisRuleSetDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\\Rule Sets</CodeAnalysisRuleSetDirectories>
    <CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisRuleDirectories>;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Static Analysis Tools\FxCop\\Rules</CodeAnalysisRuleDirectories>
    <CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>CMCv.My.MyApplication</StartupObject>
    <AssemblyTitle>CMC</AssemblyTitle>
    <Description>Cagak Melon Components for Ingrid</Description>
    <Company>ArdhGp</Company>
    <Product>CMC</Product>
    <Copyright>ArdhaGp©2023</Copyright>
    <FileVersion>2.10.20167.1127</FileVersion>
    <ImportedNamespaces>Syncfusion=False,System.Windows.Forms.DataVisualization=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,CMCv=True</ImportedNamespaces>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <AnalysisLevel>6.0-recommended</AnalysisLevel>
    <OptionStrict>On</OptionStrict>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="000. Programmer%27s Guide\**" />
    <Compile Remove="0010 - Embeded Files\080. Database\v11.0\**" />
    <Compile Remove="x64\**" />
    <Compile Remove="x86\**" />
    <EmbeddedResource Remove="000. Programmer%27s Guide\**" />
    <EmbeddedResource Remove="0010 - Embeded Files\080. Database\v11.0\**" />
    <EmbeddedResource Remove="x64\**" />
    <EmbeddedResource Remove="x86\**" />
    <None Remove="000. Programmer%27s Guide\**" />
    <None Remove="0010 - Embeded Files\080. Database\v11.0\**" />
    <None Remove="x64\**" />
    <None Remove="x86\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="2001 - Service\97 - Dialog Box\frmDialogBox.Designer.vb">
      <DependentUpon>FRMdialogbox.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\1st Party\ULbl.Designer.vb">
      <DependentUpon>ULbl.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\1st Party\ULbl.vb" />
    <Compile Update="2099 - Interface\3rd Party\PDFViewer\PDFVWR.Designer.vb">
      <DependentUpon>PDFVWR.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\3rd Party\PhotoViewer\FRMphotoViewer.Designer.vb">
      <DependentUpon>FRMphotoViewer.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\3rd Party\PhotoResizer\FRMphtrz.Designer.vb">
      <DependentUpon>FRMphtrz.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Button\Btn.Designer.vb">
      <DependentUpon>Btn.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Button\Btn.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\CheckBox\chk.Designer.vb">
      <DependentUpon>Chk.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\CheckBox\Chk.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\ComboBox\cbo.Designer.vb">
      <DependentUpon>Cbo.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\ComboBox\Cbo.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Context Menu\csmnu.Designer.vb">
      <DependentUpon>Csmnu.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Context Menu\Csmnu.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\DataGridView\dgn.Designer.vb">
      <DependentUpon>Dgn.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\DataGridView\Dgn.vb" />
    <Compile Update="2099 - Interface\Controls\DateTimePicker\dtp.Designer.vb">
      <DependentUpon>Dtp.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\DateTimePicker\Dtp.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\GroupBox\gbx.Designer.vb">
      <DependentUpon>Gbx.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\GroupBox\Gbx.vb" />
    <Compile Update="2099 - Interface\Controls\Label\lbl.Designer.vb">
      <DependentUpon>Lbl.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Label\Lbl.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\LinkLabel\Lnk.Designer.vb">
      <DependentUpon>Lnk.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\LinkLabel\Lnk.vb" />
    <Compile Update="2099 - Interface\Controls\MaskEditBox\meb.Designer.vb">
      <DependentUpon>Meb.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\MaskEditBox\Meb.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Menu Strip\mnu.Designer.vb">
      <DependentUpon>mnu.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Menu Strip\mnu.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\NumericUpDown\nud.Designer.vb">
      <DependentUpon>Nud.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\NumericUpDown\Nud.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Panel\pnl.Designer.vb">
      <DependentUpon>Pnl.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Panel\Pnl.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\PictureBox\Pbx.Designer.vb">
      <DependentUpon>Pbx.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\PictureBox\Pbx.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\ProgressBar\pgb.Designer.vb">
      <DependentUpon>Pgb.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\ProgressBar\Pgb.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\RadioButton\rdo.Designer.vb">
      <DependentUpon>Rdo.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\RadioButton\Rdo.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\SplitContainer\spc.Designer.vb">
      <DependentUpon>Spc.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\SplitContainer\Spc.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Status Strip\stt.Designer.vb">
      <DependentUpon>Stt.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\Status Strip\Stt.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\TabControl\Tbx.Designer.vb">
      <DependentUpon>Tbx.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\TabControl\Tbx.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\TextBox\txt.Designer.vb">
      <DependentUpon>Txt.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\TextBox\Txt.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="2099 - Interface\Controls\TreeView\tv.Designer.vb">
      <DependentUpon>Tv.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Controls\TreeView\Tv.vb" />
    <Compile Update="2099 - Interface\Forms\Templates\Windows7\FRMblank.Designer.vb">
      <DependentUpon>FRMblank.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Forms\Templates\Windows7\Standard\fRMstandard.Designer.vb">
      <DependentUpon>FRMstandard.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Forms\Templates\Windows7\Standard\Standard + Find + Footer\FRMstandardFindFooter.Designer.vb">
      <DependentUpon>FRMstandardFindFooter.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Forms\Templates\Windows7\Standard\Standard + Find\FRMstandardFind.Designer.vb">
      <DependentUpon>FRMstandardFind.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Forms\Templates\Windows7\Standard\Standard + Footer\Report Basic\FRMreportBasic.Designer.vb">
      <DependentUpon>FRMreportBasic.vb</DependentUpon>
    </Compile>
    <Compile Update="2099 - Interface\Forms\Templates\Windows7\Standard\Standard + Footer\FRMstandardFooter.Designer.vb">
      <DependentUpon>FRMstandardFooter.vb</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2080 - Library\001. Logo\Departement.metrop" />
    <EmbeddedResource Include="2080 - Library\001. Logo\Employee.metrop" />
    <EmbeddedResource Include="2080 - Library\001. Logo\Error.metrop" />
    <EmbeddedResource Include="2080 - Library\001. Logo\Login.metrop" />
    <EmbeddedResource Include="2080 - Library\001. Logo\Logout.metrop" />
    <EmbeddedResource Include="2080 - Library\001. Logo\Plant.metrop" />
    <EmbeddedResource Include="2080 - Library\001. Logo\TextEditor.metrop" />
    <EmbeddedResource Include="2080 - Library\001. Logo\Plant2.metrop" />
    <EmbeddedResource Include="2080 - Library\001. Logo\Storage.metrop" />
    <EmbeddedResource Include="2080 - Library\001. Logo\Qe-Logo.metrop" />
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="My Project\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
    </None>
    <EmbeddedResource Include="2002 - System\000 - Security\Manual+Source\Security Engine Source.pdf" />
    <EmbeddedResource Include="2001 - Service\01 - Database\01 - Connection\Manual+Source\MSSQL2008 Manual.pdf" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="0010 - Embeded Files\080. Database\Classic\" />
    <Folder Include="2001 - Service\02 - SOAP\" />
    <Folder Include="2001 - Service\03 - Web\" />
    <Folder Include="2001 - Service\04 - Map\Bing\" />
    <Folder Include="2001 - Service\04 - Map\Google\" />
    <Folder Include="2002 - System\110 - File Processor\Limiter\" />
    <Folder Include="2002 - System\900 - Application\" />
    <Folder Include="2091 - Class\01 - Database\02 - SQL Server 2008\" />
    <Folder Include="2099 - Interface\Controls\MergerToolStrips\" />
    <Folder Include="2099 - Interface\Controls\TextEditor\" />
    <Folder Include="2099 - Interface\Forms\Templates\Windows10\" />
    <Folder Include="SqlServerTypes\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\Button\Btn.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\DateTimePicker\Dtp.ico" />
    <EmbeddedResource Include="2099 - Interface\Controls\Label\Lbl.ico" />
    <EmbeddedResource Include="2099 - Interface\Controls\TextBox\Txt.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\DataGridView\Dgn.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\GroupBox\Gbx.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\LinkLabel\Lnk.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\ComboBox\Cbo.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\MaskEditBox\Meb.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\CheckBox\Chk.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\RadioButton\Rdo.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\ProgressBar\Pgb.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="2099 - Interface\Controls\Panel\Pnl.ico" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="2099 - Interface\Controls\NumericUpDown\Nud.ico" />
    <Content Include="2099 - Interface\Controls\PictureBox\Pbx.ico" />
    <EmbeddedResource Include="Resources\EDIT_002_512_icon .png" />
    <EmbeddedResource Include="Resources\Save_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\OpenFile_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\FitPage_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\FitWidth_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\ZoomIn_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\ZoomOut_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\ArrowRight_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\ArrowLeft_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\ArrowLast_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\ArrowFirst_001_24_FFFFFFFF_FF5423C3.png" />
    <EmbeddedResource Include="Resources\Resize_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\petronas_green.png" />
    <EmbeddedResource Include="Resources\Question_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Information_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Alert_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Error_002_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodeintelligentmail.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodefourstate.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodeean13.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodeean8.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodedatamatrix.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodecode128.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodecode93.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodecode39.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodecode11.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodecodabar.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodeazteccode.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodeupca.png" />
    <EmbeddedResource Include="Resources\TED_16_barcoderoyalmail.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodeqrcode.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodepostnet.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodeplanet.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodepdf417.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodemicropdf.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodemaxicode.png" />
    <EmbeddedResource Include="Resources\TED_16_barcodeinterleaved2of5.png" />
    <EmbeddedResource Include="Resources\TED_16_chartgridlinesmajorhor.png" />
    <EmbeddedResource Include="Resources\TED_16_chartformat.png" />
    <EmbeddedResource Include="Resources\TED_16_chartdatatable.png" />
    <EmbeddedResource Include="Resources\TED_16_chartdatalabels.png" />
    <EmbeddedResource Include="Resources\TED_16_chartcolumn3d.png" />
    <EmbeddedResource Include="Resources\TED_16_chartcolumn.png" />
    <EmbeddedResource Include="Resources\TED_16_chartbelowaxistitle.png" />
    <EmbeddedResource Include="Resources\TED_16_chartbar3d.png" />
    <EmbeddedResource Include="Resources\TED_16_chartbar.png" />
    <EmbeddedResource Include="Resources\TED_16_chartaxes.png" />
    <EmbeddedResource Include="Resources\TED_16_chartarea3d.png" />
    <EmbeddedResource Include="Resources\TED_16_chartarea.png" />
    <EmbeddedResource Include="Resources\TED_16_chart.png" />
    <EmbeddedResource Include="Resources\TED_16_charttitlemain.png" />
    <EmbeddedResource Include="Resources\TED_16_chartsetdatarelation.png" />
    <EmbeddedResource Include="Resources\TED_16_chartpie3d.png" />
    <EmbeddedResource Include="Resources\TED_16_chartpie.png" />
    <EmbeddedResource Include="Resources\TED_16_chartline3d.png" />
    <EmbeddedResource Include="Resources\TED_16_chartline.png" />
    <EmbeddedResource Include="Resources\TED_16_chartlegend.png" />
    <EmbeddedResource Include="Resources\TED_16_chartlayout.png" />
    <EmbeddedResource Include="Resources\TED_16_chartgridlinesmajorvert.png" />
    <EmbeddedResource Include="Resources\TED_16_undo.png" />
    <EmbeddedResource Include="Resources\TED_16_textframe.png" />
    <EmbeddedResource Include="Resources\TED_16_tabs.png" />
    <EmbeddedResource Include="Resources\TED_16_tablegridlines.png" />
    <EmbeddedResource Include="Resources\TED_16_tabledialog.png" />
    <EmbeddedResource Include="Resources\TED_16_table.png" />
    <EmbeddedResource Include="Resources\TED_16_styledialog.png" />
    <EmbeddedResource Include="Resources\TED_16_splittablecells.png" />
    <EmbeddedResource Include="Resources\TED_16_splittablebelow.png" />
    <EmbeddedResource Include="Resources\TED_16_splittableabove.png" />
    <EmbeddedResource Include="Resources\TED_16_splittable.png" />
    <EmbeddedResource Include="Resources\TED_16_spelling.png" />
    <EmbeddedResource Include="Resources\TED_16_setlanguage.png" />
    <EmbeddedResource Include="Resources\TED_16_selecttablerow.png" />
    <EmbeddedResource Include="Resources\TED_16_selecttablecol.png" />
    <EmbeddedResource Include="Resources\TED_16_selecttablecell.png" />
    <EmbeddedResource Include="Resources\TED_16_selecttable.png" />
    <EmbeddedResource Include="Resources\TED_16_save.png" />
    <EmbeddedResource Include="Resources\TED_16_replace.png" />
    <EmbeddedResource Include="Resources\TED_16_redo.png" />
    <EmbeddedResource Include="Resources\TED_16_printpreview.png" />
    <EmbeddedResource Include="Resources\TED_16_print.png" />
    <EmbeddedResource Include="Resources\TED_16_paste.png" />
    <EmbeddedResource Include="Resources\TED_16_paragraphsettings.png" />
    <EmbeddedResource Include="Resources\TED_16_pageviewprint.png" />
    <EmbeddedResource Include="Resources\TED_16_pageviewnormal.png" />
    <EmbeddedResource Include="Resources\TED_16_pagenumbertop.png" />
    <EmbeddedResource Include="Resources\TED_16_pagenumberbottom.png" />
    <EmbeddedResource Include="Resources\TED_16_pageframedialog.png" />
    <EmbeddedResource Include="Resources\TED_16_pagedialog.png" />
    <EmbeddedResource Include="Resources\TED_16_pagecolumnstwo.png" />
    <EmbeddedResource Include="Resources\TED_16_pagebreak.png" />
    <EmbeddedResource Include="Resources\TED_16_options.png" />
    <EmbeddedResource Include="Resources\TED_16_open.png" />
    <EmbeddedResource Include="Resources\TED_16_newpage.png" />
    <EmbeddedResource Include="Resources\TED_16_mergetablecells.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergeshowfieldtext.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergeshowfieldcodes.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergenextiffield.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergenextfield.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergeinsertfield.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergeincludetextfield.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergeiffield.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergehighlightfields.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergefieldproperties.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergedeletefield.png" />
    <EmbeddedResource Include="Resources\TED_16_mailmergedatefield.png" />
    <EmbeddedResource Include="Resources\TED_16_listdialog.png" />
    <EmbeddedResource Include="Resources\TED_16_languagedetection.png" />
    <EmbeddedResource Include="Resources\TED_16_inserttablerowbelow.png" />
    <EmbeddedResource Include="Resources\TED_16_inserttablerowabove.png" />
    <EmbeddedResource Include="Resources\TED_16_inserttablecolright.png" />
    <EmbeddedResource Include="Resources\TED_16_inserttablecolleft.png" />
    <EmbeddedResource Include="Resources\TED_16_insertpagenumber.png" />
    <EmbeddedResource Include="Resources\TED_16_insertlinebreak.png" />
    <EmbeddedResource Include="Resources\TED_16_inserthyperlink.png" />
    <EmbeddedResource Include="Resources\TED_16_insertfile.png" />
    <EmbeddedResource Include="Resources\TED_16_insertbookmark.png" />
    <EmbeddedResource Include="Resources\TED_16_indentincrease.png" />
    <EmbeddedResource Include="Resources\TED_16_indentdecrease.png" />
    <EmbeddedResource Include="Resources\TED_16_image.png" />
    <EmbeddedResource Include="Resources\TED_16_hyphenation.png" />
    <EmbeddedResource Include="Resources\TED_16_hfdialog.png" />
    <EmbeddedResource Include="Resources\TED_16_help.png" />
    <EmbeddedResource Include="Resources\TED_16_header.png" />
    <EmbeddedResource Include="Resources\TED_16_formlayoutrtl.png" />
    <EmbeddedResource Include="Resources\TED_16_formlayoutltr.png" />
    <EmbeddedResource Include="Resources\TED_16_find.png" />
    <EmbeddedResource Include="Resources\TED_16_export.png" />
    <EmbeddedResource Include="Resources\TED_16_exit.png" />
    <EmbeddedResource Include="Resources\TED_16_edithyperlink.png" />
    <EmbeddedResource Include="Resources\TED_16_deletetablerow.png" />
    <EmbeddedResource Include="Resources\TED_16_deletetablecol.png" />
    <EmbeddedResource Include="Resources\TED_16_deletetablecell.png" />
    <EmbeddedResource Include="Resources\TED_16_deletetable.png" />
    <EmbeddedResource Include="Resources\TED_16_deletepagenumber.png" />
    <EmbeddedResource Include="Resources\TED_16_delete.png" />
    <EmbeddedResource Include="Resources\TED_16_cut.png" />
    <EmbeddedResource Include="Resources\TED_16_copy.png" />
    <EmbeddedResource Include="Resources\TED_16_charactersettings.png" />
    <EmbeddedResource Include="Resources\TED_16_zoom.png" />
    <EmbeddedResource Include="Resources\TextEditor_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Error_001_90_FFFFFFFF_.png" />
    <EmbeddedResource Include="2080 - Library\001. Logo\QeLogo16.ico" />
    <EmbeddedResource Include="2080 - Library\001. Logo\QeLogo16Red.ico" />
    <EmbeddedResource Include="2002 - System\000 - Security\Manual+Source\Security Engine Manual.txt" />
    <EmbeddedResource Include="Resources\FailToLoad_001_24_FFFFFFFF_.png" />
    <EmbeddedResource Include="Resources\Loading_001_24_FFFFFFFF_.gif" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{94E38DFF-614B-4CBD-B67C-F211BB35CE8B}" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.6">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.6 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="NETCore.Encrypt" Version="2.1.1" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.24" />
    <PackageReference Include="Syncfusion.Grid.Windows" Version="33.2.6" />
    <PackageReference Include="Syncfusion.Licensing" Version="33.2.6" />
    <PackageReference Include="Syncfusion.PdfViewer.Windows" Version="33.2.6" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="33.2.6" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="33.2.6" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.0" />
    <PackageReference Include="System.Data.OleDb" Version="10.0.7" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.7" />
    <PackageReference Include="System.Management" Version="10.0.0" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="2099 - Interface\Controls\Tool Strip\too.Designer.vb" />
    <Compile Remove="2099 - Interface\Controls\Tool Strip\too.vb" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="0010 - Embeded Files\080. Database\Classic\CATALOG.mdb" />
    <None Remove="0010 - Embeded Files\080. Database\Classic\DEV_CATALOG.mdb" />
    <None Remove="0010 - Embeded Files\080. Database\Classic\ERRLOG.mdb" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="Syncfusion" />
    <Import Include="System.Windows.Forms.DataVisualization" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bridge\Bridge.csproj" />
    <ProjectReference Include="..\LibApp\LibApp.vbproj" />
  </ItemGroup>
</Project>