<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LibAPI</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <VBOptionStrict>On</VBOptionStrict>
    <VBOptionExplicit>On</VBOptionExplicit>
    <VBOptionInfer>Off</VBOptionInfer>
    <OptionStrict>On</OptionStrict>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.100.2" />
    <PackageReference Include="MagikaNet" Version="2.0.1" />
  </ItemGroup>

</Project>
