<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <StartupObject>IngridLauncher.My.MyApplication</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <LangVersion>latest</LangVersion>
    <VBOptionStrict>On</VBOptionStrict>
    <VBOptionExplicit>On</VBOptionExplicit>
    <VBOptionInfer>Off</VBOptionInfer>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <FileVersion>0.0.0.0</FileVersion>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
    <ApplicationIcon>Resources\ingrid_icon_2.ico</ApplicationIcon>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <OptionStrict>On</OptionStrict>
    <AssemblyName>Ingrid</AssemblyName>
    <UserSecretsId>b286ff11-5119-4718-8b6d-f6fc6eb0a39a</UserSecretsId>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineDebug>True</DefineDebug>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DefineDebug>True</DefineDebug>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineDebug>True</DefineDebug>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineDebug>False</DefineDebug>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DefineDebug>False</DefineDebug>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineDebug>False</DefineDebug>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\svg-404.svg" />
    <None Remove="Resources\svg-CCIN.svg" />
    <None Remove="Resources\svg-CDIN.svg" />
    <None Remove="Resources\svg-company.svg" />
    <None Remove="Resources\svg-department.svg" />
    <None Remove="Resources\svg-EDIT.svg" />
    <None Remove="Resources\svg-EPLS.svg" />
    <None Remove="Resources\svg-images.svg" />
    <None Remove="Resources\svg-key.svg" />
    <None Remove="Resources\svg-lock.svg" />
    <None Remove="Resources\svg-LOGIN.svg" />
    <None Remove="Resources\svg-LOGIN02.svg" />
    <None Remove="Resources\svg-play-fill.svg" />
    <None Remove="Resources\svg-x-circle-fill.svg" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\ingrid_icon_2.ico" />
    <Content Include="Resources\svg-404.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-CCIN.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-CDIN.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-company.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-department.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-EDIT.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-EPLS.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-images.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-key.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-lock.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-LOGIN.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-LOGIN02.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-play-fill.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\svg-x-circle-fill.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="svg" Version="3.4.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Vb\Ingrid.vbproj" />
    <ProjectReference Include="..\Bridge\Bridge.csproj" />
    <ProjectReference Include="..\Connect\Connect.vbproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="My Project\Settings.settings">
      <CustomToolNamespace>My</CustomToolNamespace>
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
</Project>