CREATE TABLE [dbo].[xsl_mb51] (
    [mb51_postingdate]       DATE          NULL,
    [mb51_timeofentry]       TIME (7)      NULL,
    [mb51_entrydate]         DATE          NULL,
    [mb51_documentdate]      DATE          NULL,
    [mb51_mm]                VARCHAR (255) NULL,
    [mb51_materialname]      VARCHAR (255) NULL,
    [mb51_plant]             VARCHAR (255) NULL,
    [mb51_valuationtype]     VARCHAR (255) NULL,
    [mb51_sloc]              VARCHAR (255) NULL,
    [mb51_mvt]               VARCHAR (255) NULL,
    [mb51_mvttext]           VARCHAR (255) NULL,
    [mb51_spcl]              VARCHAR (255) NULL,
    [mb51_matdoc]            VARCHAR (255) NULL,
    [mb51_matdocitem]        INT           NULL,
    [mb51_qty]               INT           NULL,
    [mb51_uom]               VARCHAR (255) NULL,
    [mb51_amountinlc]        VARCHAR (255) NULL,
    [mb51_po]                VARCHAR (255) NULL,
    [mb51_so]                VARCHAR (255) NULL,
    [mb51_vendor]            VARCHAR (255) NULL,
    [mb51_order]             VARCHAR (255) NULL,
    [mb51_rsv]               VARCHAR (255) NULL,
    [mb51_rsvitem]           INT           NULL,
    [mb51_wbs]               VARCHAR (255) NULL,
    [mb51_costcenter]        VARCHAR (255) NULL,
    [mb51_text]              VARCHAR (255) NULL,
    [mb51_docheadertext]     VARCHAR (255) NULL,
    [mb51_operationactivity] VARCHAR (255) NULL,
    [mb51_reasonformovement] VARCHAR (255) NULL,
    [mb51_receiptindicator]  VARCHAR (255) NULL,
    [mb51_reference]         VARCHAR (255) NULL
);

