# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net.

# Important notice
# $(var_g_Ingridversion_major) : ingrid major version
# $(var_g_Ingridversion_minor) : publishing number
# $(var_g_Ingridversion_build) : build / compile number
# $(var_g_Ingridversion_revision) : failed build / compile number
# $(var_NET) : .NET version
# $(var_BuildConfiguration) : build configuration (Debug/Release)
# $(var_Platform) : platform configuration (Any CPU/x86/x64)

trigger:
- none

pool:
  vmImage: 'windows-latest'

#Assigning variables from Environment
variables:
- group: global_variables

- name: var_p_Email
  value: $[variables.var_g_Email]
- name: var_p_DownloadCenter
  value: $[variables.var_g_DownloadCenter]

- name: var_p_Platform
  value: $[variables.var_Platform]
- name: var_p_BuildConfiguration
  value: $[variables.var_BuildConfiguration]

- name: var_p_Ingridversion_major
  value: $[variables.var_g_Ingridversion_major]
- name: var_p_Ingridversion_minor
  value: $[variables.var_g_Ingridversion_minor]
- name: var_p_Ingridversion_build
  value: $[variables.var_g_Ingridversion_build]
- name: var_p_Ingridversion_revision
  value: $[variables.var_g_Ingridversion_revision]

- name: var_p_BetterStack_Log
  value: $[variables.var_g_BetterStack_Log]
- name: var_p_SyncfusionKey
  value: $[variables.var_g_SyncfusionKey]
- name: var_p_Salt
  value: $[variables.var_g_Salt]

- name: var_p_TOKEN_GITHUB
  value: $[variables.var_g_TOKEN_GITHUB]
- name: var_p_TOKEN_AZURE
  value: $[variables.var_g_TOKEN_AZURE]

steps:

- task: ado-discord-webhook@2
  displayName: 'Step-01: Start compiling'
  condition: always()
  inputs:
    webhookId: '$(var_g_Discord_WebhookID)'
    webhookKey: '$(var_g_Discord_WebhookKey)'
    name: 'Azure Devops'
    embeds: |
      [
        {
          "type": "rich",
          "title": "[$(System.TeamProject):$(Build.SourceBranchName)] • Start compiling Ingrid App",
          "description": "Ingrid ver. $(var_g_Ingridversion_major).$(var_g_Ingridversion_minor).$(var_g_Ingridversion_build) for $(var_Platform) platform.",
          "color": 0xffde59,
          "fields": [
            {
              "name": "Build.Pipeline",
              "value": "$(Build.Repository.Name)",
              "inline": true
            },
            {
              "name": "Build.Number",
              "value": "$(Build.BuildNumber)",
              "inline": true
            }
          ],
          "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
        }
      ]

#Installing Nuget
- task: NuGetToolInstaller@1
  displayName: 'Step-02: Install Nuget'
  inputs:
    versionSpec: 
    checkLatest: true

#List of Files in $(Build.SourcesDirectory)
- task: CmdLine@2
  displayName: 'Step-03: Pre-Build File List in $(Build.SourcesDirectory)'
  inputs:
    script: |
      echo "File List - $(Build.SourcesDirectory)"
      
      cd $(Build.SourcesDirectory)
      dir /b /s /A-D /o:gn

#Nuget Restore
- task: NuGetCommand@2
  displayName: 'Step-04: Restore NuGet'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    noCache: false
    nugetConfigPath: './Apps/Core/Vb/NuGet.config'
    externalFeedCredentials: 'ingrid'

#Replacing SALT Key
- task: ReplaceInFilesTextByText@2
  displayName: 'Step-05: Replacing: BridgeKey.Salt'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'config.GetSection("KEYS")["SALT"]'
    parameterReplaceText: '"$(var_g_Salt)"'
    parameterTypeOfSearch: 'filesSearchPattern'
    parameterFilesPattern: '*.cs'

#Replacing Syncfusion Key
- task: ReplaceInFilesTextByText@2
  displayName: 'Step-06: Replacing: BridgeKey.Syncfusion'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'config.GetSection("KEYS")["SYNCFUSION"]'
    parameterReplaceText: '"$(var_g_SyncfusionKey)"'
    parameterTypeOfSearch: 'filesSearchPattern'
    parameterFilesPattern: '*.cs'

#Replacing BetterStack Key
- task: ReplaceInFilesTextByText@2
  displayName: 'Step-07: Replacing: BridgeKey.BetterStackLog'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'config.GetSection("KEYS")["BETTERSTACK_LOG"]'
    parameterReplaceText: '"$(var_g_BetterStack_Log)"'
    parameterTypeOfSearch: 'filesSearchPattern'
    parameterFilesPattern: '*.cs'

- task: ReplaceInFilesTextByText@2
  displayName: 'Step-08: Replacing: BridgeKey.BetterStackHeartbeats'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'config.GetSection("KEYS")["BETTERSTACK_HEARTBEATS"]'
    parameterReplaceText: '"$(var_g_BetterStack_Heartbeats)"'
    parameterTypeOfSearch: 'filesSearchPattern'
    parameterFilesPattern: '*.cs'

#Replacing Version: Major
- task: ReplaceInFilesTextByText@2
  displayName: 'Step-09: Replacing: {Version.Major}'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'My.Application.Info.Version.Major'
    parameterReplaceText: '$(var_g_Ingridversion_major)'
    parameterTypeOfSearch: 'filesSearchPattern'
    parameterFilesPattern: '*.vb'

#Replacing Version: Minor
- task: ReplaceInFilesTextByText@2
  displayName: 'Step-10: Replacing: {Version.Minor}'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'My.Application.Info.Version.Minor'
    parameterReplaceText: '$(var_g_Ingridversion_minor)'
    parameterTypeOfSearch: 'filesSearchPattern'
    parameterFilesPattern: '*.vb'

#Replacing Version: Build
- task: ReplaceInFilesTextByText@2
  displayName: 'Step-11: Replacing: {Version.Build}'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'My.Application.Info.Version.Build'
    parameterReplaceText: '$(var_g_Ingridversion_build)'
    parameterTypeOfSearch: 'filesSearchPattern'
    parameterFilesPattern: '*.vb'

#Replacing Version: Revision
- task: ReplaceInFilesTextByText@2
  displayName: 'Step-12: Replacing: {Version.Revision}'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'My.Application.Info.Version.Revision'
    parameterReplaceText: '$(var_g_Ingridversion_revision)'
    parameterTypeOfSearch: 'filesSearchPattern'
    parameterFilesPattern: '*.vb'

#Replacing DownloadCenterURL
- task: ReplaceInFilesTextByText@2
  displayName: 'Step-13: Replacing: {DownloadCenter_Url}'
  inputs:
    parameterSearchDirectory: '$(Build.SourcesDirectory)'
    parameterSearchText: 'My.Settings.ConnectionURL'
    parameterReplaceText: '"$(var_g_DownloadCenter)"'
    parameterTypeOfSearch: 'filesSearchPattern'
    parameterFilesPattern: '*.vb'

#Checking new value from variables
- task: CmdLine@2
  displayName: 'Step-14: Check Text Replacement'
  inputs:
    script: |
      echo BetterStackLog: $(var_g_BetterStack_Log)
      echo Major: $(var_g_Ingridversion_major)
      echo Minor: $(var_g_Ingridversion_minor)
      echo Build: $(var_g_Ingridversion_build)
      echo Revision: $(var_g_Ingridversion_revision)
      echo DownloadCenter: $(var_g_DownloadCenter)

#Review content of code
- #task: CmdLine@2
  #displayName: 'Reviewing Codes'
  #inputs:
    #script: |
      #echo "File List - Ingrid-CI-Build"
      
      #cd $(Build.SourcesDirectory)
      #dir /b /s /A-D /o:gn
      #echo "Reading CMC\Global.vb"
      #echo "---------------------------"
      #more ".\Apps\Components\CMC\2090 - Module\Global.vb"
      #echo "---------------------------"
      #echo "Reading Apps\Core\Module\Global.vb"
      #echo "---------------------------"
      #more ".\Apps\Core\Vb\020. Module\Global.vb"

#Build Ingrid App
- task: VSBuild@1
  displayName: 'Step-15: Build and Publish'
  inputs:
    solution: '**\*.sln'
    #msbuildArgs: '/t:Publish /p:BootstrapperEnabled=True /p:IsWebBootstrapper=True /p:PublishProtocol=ClickOnce /p:Install=True /p:CreateDesktopShortcut=True /p:InstallFrom=Web /p:GenerateManifests=True /p:BootstrapperComponents="Microsoft.NetCore.DesktopRuntime.$(var_NET).x86" /p:InstallUrl="https://ingrid-blob.s3.us-west-004.backblazeb2.com/files/" /p:PublishProfile="$(Build.SourcesDirectory)\Ingrid\Apps\Components\Ingrid-Launcher\My Project\PublishProfiles\ClickOnceProfile.pubxml" /p:PublishUrl="$(Build.SourcesDirectory)\Ingrid\Apps\Components\Ingrid-Launcher\bin\$(var_BuildConfiguration)\net$(var_NET).0-windows\package\" /p:PublishDir="$(Build.SourcesDirectory)\Ingrid\Apps\Components\Ingrid-Launcher\bin\$(var_BuildConfiguration)\net$(var_NET).0-windows7.0\publish\" /p:ApplicationVersion="$(var_g_Ingridversion_major).$(var_g_Ingridversion_minor).$(var_g_Ingridversion_build).$(var_g_Ingridversion_revision)"'
    msbuildArgs: '/t:Publish /p:BootstrapperEnabled=True /p:IsWebBootstrapper=True /p:PublishProtocol=ClickOnce /p:Install=True /p:UpdateEnabled=true /p:UpdateMode=Foreground /p:CreateDesktopShortcut=True /p:InstallFrom=Web /p:GenerateManifests=True /p:BootstrapperComponents="Microsoft.NetCore.DesktopRuntime.$(var_NET).x86" /p:InstallUrl="https://ingrid-blob.s3.us-west-004.backblazeb2.com/files/" /p:PublishProfile="$(Build.SourcesDirectory)\Apps\Components\Ingrid-Launcher\My Project\PublishProfiles\ClickOnceProfile.pubxml" /p:PublishUrl="$(Build.SourcesDirectory)\Apps\Components\Ingrid-Launcher\bin\$(var_BuildConfiguration)\net$(var_NET).0-windows\package\" /p:PublishDir="$(Build.SourcesDirectory)\Apps\Components\Ingrid-Launcher\bin\$(var_BuildConfiguration)\net$(var_NET).0-windows7.0\publish\" /p:ApplicationVersion="$(var_g_Ingridversion_major).$(var_g_Ingridversion_minor).$(var_g_Ingridversion_build).$(var_g_Ingridversion_revision)"'
    #$(Build.ArtifactStagingDirectory)
    platform: '$(var_Platform)'
    configuration: '$(var_BuildConfiguration)'
    clean: true
    maximumCpuCount: true
    createLogFile: true

#List of File in $(Build.SourcesDirectory)
- task: CmdLine@2
  displayName: 'Step-16: File List - Post Build $(Build.SourcesDirectory)'
  inputs:
    script: |
      echo "---------------------------"
      echo "Print File List - Post Build"
      echo "---------------------------"
      cd $(Build.SourcesDirectory)\Apps\Components\Ingrid-Launcher\bin\$(var_BuildConfiguration)\net$(var_NET).0-windows7.0\publish\
      dir /b /s /A-D /o:gn

#Packing deployment to Artifact Directory
- task: CopyFiles@2
  displayName: 'Step-17: Copy Files to.. $(build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\Apps\Components\Ingrid-Launcher\bin\$(var_BuildConfiguration)\net$(var_NET).0-windows7.0\publish\'
    Contents: '**'
    TargetFolder: '$(build.ArtifactStagingDirectory)'

# Compressing Artifact to ingrid-offline.zip
- task: ArchiveFiles@2
  displayName: 'Step-17B: Compressing Files'
  inputs:
    rootFolderOrFile: '$(build.ArtifactStagingDirectory)\'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(build.ArtifactStagingDirectory)/ingrid-offline.zip'
    replaceExistingArchive: true


#List of File in $(Build.SourcesDirectory)
- task: CmdLine@2
  displayName: 'Step-18: File List - Post Copy $(Build.SourcesDirectory)'
  inputs:
    script: |
      echo "---------------------------"
      echo "Reading Artifact Directory"
      echo "---------------------------"
      cd $(build.ArtifactStagingDirectory)
      dir /b /s /A-D /o:gn
      echo "---------------------------"
      echo "Reading Ingrid.Application"
      echo "---------------------------"
      cd $(Build.SourcesDirectory)
      more ".\Apps\Components\Ingrid-Launcher\bin\$(var_BuildConfiguration)\net$(var_NET).0-windows7.0\publish\Ingrid.application"

- task: ado-discord-webhook@2
  displayName: 'Step-19: Transfering application to Backblaze'
  condition: succeeded()
  inputs:
    webhookId: '$(var_g_Discord_WebhookID)'
    webhookKey: '$(var_g_Discord_WebhookKey)'
    name: 'Azure Devops'
    embeds: |
      [
        {
          "type": "rich",
          "title": "Transfering application",
          "description": "Transfering Ingrid v$(var_g_Ingridversion_major).$(var_g_Ingridversion_minor) to Backblaze Cloud.",
          "color": 0xee27f5,
          "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
        }
      ]

- task: PowerShell@2
  displayName: 'Step-20: Copy Files to BackBlaze'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "=== Installing AWS CLI ==="
      python -m pip install --upgrade pip
      pip install awscli

      Write-Host "=== AWS CLI Version ==="
      aws --version

      Write-Host "=== Checking publish output folder ==="
      Get-ChildItem -Recurse "$(build.ArtifactStagingDirectory)" | Select-Object FullName

      Write-Host "=== Removing old files from Backblaze ==="
      aws s3 rm "s3://ingrid-blob/files/" `
        --recursive `
        --endpoint-url https://s3.us-west-004.backblazeb2.com

      Write-Host "=== Uploading new files ==="
      aws s3 cp "$(build.ArtifactStagingDirectory)/" `
        "s3://ingrid-blob/files/" `
        --recursive `
        --endpoint-url https://s3.us-west-004.backblazeb2.com
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


# No longer used due to reducing repo size and complexity, but kept for reference.
# This task is moved to Step-17B above to compress the artifact before publishing to Backblaze and Github Pages.
# Compressing Artifact to Zip
- #task: ArchiveFiles@2
  #displayName: 'Step-21: Compressing Files'
  #inputs:
    #rootFolderOrFile: '$(build.ArtifactStagingDirectory)\'
    #includeRootFolder: true
    #archiveType: 'zip'
    #archiveFile: '$(build.ArtifactStagingDirectory)/publish/zip/ingrid-offline.zip'
    #replaceExistingArchive: true

# Activate this task if you want to publish the artifact to Azure DevOps artifacts for release via FTP or other means. Currently, it's commented out because the pipeline is set up to publish directly to Backblaze and Github Pages.
#Publish Artifact for Relase via FTP
# - task: PublishBuildArtifacts@1
#  displayName: 'Step-22: Publish Artifact.. ingrid-artifact'
#  inputs:
#    PathtoPublish: '$(build.ArtifactStagingDirectory)'
#    ArtifactName: 'ingrid-artifact'
#    publishLocation: 'Container'

# Send Discord notification for transferring application to Github Pages
- task: ado-discord-webhook@2
  displayName: 'Step-23: Sending Discord Notification'
  condition: succeeded()
  inputs:
    webhookId: '$(var_g_Discord_WebhookID)'
    webhookKey: '$(var_g_Discord_WebhookKey)'
    name: 'Azure Devops'
    embeds: |
      [
        {
          "type": "rich",
          "title": "Transfering application",
          "description": "Transfering Ingrid v$(var_g_Ingridversion_major).$(var_g_Ingridversion_minor) to Github.io page.",
          "color": 0xee27f5,
          "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
        }
      ]

# This task is disabled and moved to Step-20 above to reduce the number of steps and complexity in the pipeline. The artifact is now compressed before being uploaded to Backblaze.
# Direct publish ingrid-offline.zip to Github Pages
- #task: GitHubPagesPublish@1
  #displayName: 'Step-24: Publishing App To Github Pages'
  #inputs:
    #docPath: '$(build.ArtifactStagingDirectory)\publish\zip\ingrid-offline.zip'
    #githubusername: 'ardhagp'
    #githubemail: '$(var_g_Email)'
    #githubaccesstoken: '$(var_g_TOKEN_GITHUB)'
    #repositoryname: 'ingrid'
    #branchname: 'publish'
    #commitmessage: 'Release ver. $(var_g_Ingridversion_major).$(var_g_Ingridversion_minor).$(var_g_Ingridversion_build)'

# This task is disabled because the pipeline is set up to publish directly to Backblaze and Github Pages. If you want to publish to Azure Static Web Apps, you can uncomment this task and configure it accordingly.
#- task: AzureStaticWebApp@0
#  displayName: 'Step-25: Publishing Static Web App'
#  inputs:
#    workingDirectory: '$(build.ArtifactStagingDirectory)\*'
#    app_location: '/'
#    api_location: '/api'
#    skip_app_build: true
#    skip_api_build: true
#    is_static_export: true
#    azure_static_web_apps_api_token: '$(var_g_TOKEN_SWA)'
#    production_branch: 'publish'

# Sending Discord notification for successful build and publish
- task: ado-discord-webhook@2
  displayName: 'Step-26: Sending Discord Notification for Success'
  condition: succeeded()
  inputs:
    webhookId: '$(var_g_Discord_WebhookID)'
    webhookKey: '$(var_g_Discord_WebhookKey)'
    name: 'Azure Devops'
    embeds: |
      [
        {
          "type": "rich",
          "title": "[$(System.TeamProject):$(Build.SourceBranchName)] • Compile and Publish Success!",
          "description": "Ingrid ver. $(var_g_Ingridversion_major).$(var_g_Ingridversion_minor) for $(var_Platform) platform.",
          "color": 0x00ff00,
          "fields": [
            {
              "name": "Build.Pipeline",
              "value": "$(Build.Repository.Name)",
              "inline": true
            },
            {
              "name": "Build.Number",
              "value": "$(Build.BuildNumber)",
              "inline": true
            }
          ],
          "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
        }
      ]

# Sending Discord notification for failed build and publish
- task: ado-discord-webhook@2
  displayName: 'Step-27: Sending Discord Notification for Failure'
  condition: failed()
  inputs:
    webhookId: '$(var_g_Discord_WebhookID)'
    webhookKey: '$(var_g_Discord_WebhookKey)'
    name: 'Azure Devops'
    embeds: |
      [
        {
          "type": "rich",
          "title": "[$(System.TeamProject):$(Build.SourceBranchName)] • Compile and Publish failed",
          "description": "Ingrid v$(var_g_Ingridversion_major).$(var_g_Ingridversion_minor) for $(var_Platform) platform.",
          "color": 0xff0000,
          "fields": [
            {
              "name": "Build.Pipeline",
              "value": "$(Build.Repository.Name)",
              "inline": true
            },
            {
              "name": "Revision.Number",
              "value": "$(var_g_Ingridversion_revision)",
              "inline": true
            }
          ],
          "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
        }
      ]

# Updating {Version.Minor} for next build
- task: update-variablegroup-variable@0
  condition: succeeded()
  displayName: 'Step-28: Bump {Version.Minor} For Next Build'
  inputs:
    variableGroupName: 'global_variables'
    variableName: 'var_g_Ingridversion_minor'
    variableDataType: 'int'
    newVariableValueInInt: 1
    usePAT: true
    patValue: '$(var_g_TOKEN_AZURE)'

# Updating {Version.Revision} for next build
- task: update-variablegroup-variable@0
  condition: failed()
  displayName: 'Step-29: Bump {Version.Revision} For Next Build'
  inputs:
    variableGroupName: 'global_variables'
    variableName: 'var_g_Ingridversion_revision'
    variableDataType: 'int'
    newVariableValueInInt: 1
    usePAT: true
    patValue: '$(var_g_TOKEN_AZURE)'
