# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./Apps/Components/Ingrid-Launcher/IngridLauncher.vbproj
    - name: Build
      run: msbuild ./Apps/Components/Ingrid-Launcher/IngridLauncher.vbproj -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: Test
      run: dotnet test ./Apps/Components/Ingrid-Launcher/IngridLauncher.vbproj --no-build --verbosity normal
