# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# Important note:
# ${{ env.VAR_G_INGRIDVERSION_MAJOR }} : ingrid major version
# ${{ env.VAR_G_INGRIDVERSION_MINOR }} : publishing number
# ${{ env.VAR_G_INGRIDVERSION_BUILD }} : build / compile number
# ${{ env.VAR_G_INGRIDVERSION_REVISION }} : failed build / compile number
# ${{ env.VAR_G_NET }} : .NET version
# ${{ env.VAR_G_BUILDCONFIGURATION }} : build configuration (Debug/Release)
# ${{ env.VAR_G_PLATFORM }} : platform configuration (Any CPU/x86/x64)

name: Release

on:
  workflow_dispatch:

jobs:

  build:
    environment: Ingrid_Env

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Path: "./Apps/Core/Vb"
      Solution_Name: "Ingrid.sln"
      Solution_Nuget: "NuGet.config"
      VAR_G_BUILDCONFIGURATION: ${{ vars.VAR_G_BUILDCONFIGURATION }}
      VAR_G_INGRIDVERSION_MAJOR: ${{ vars.VAR_G_INGRIDVERSION_MAJOR }}
      VAR_G_INGRIDVERSION_MINOR: ${{ vars.VAR_G_INGRIDVERSION_MINOR }}
      VAR_G_INGRIDVERSION_BUILD: ${{ vars.VAR_G_INGRIDVERSION_BUILD }}
      VAR_G_INGRIDVERSION_REVISION: ${{ vars.VAR_G_INGRIDVERSION_REVISION }}
      VAR_G_NET: ${{ vars.VAR_G_NET }}
      VAR_G_PLATFORM: ${{ vars.VAR_G_PLATFORM }}
      VAR_G_DOWNLOADCENTER_URL: ${{ vars.VAR_G_DOWNLOADCENTER_URL }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      with:
        nuget-version: latest
        
    - name: Checking Variables
      shell: cmd
      run: |
        echo =============================================================
        echo           Values used in the build process
        echo =============================================================
        echo Configuration : %VAR_G_BUILDCONFIGURATION%
        echo Version.Major : %VAR_G_INGRIDVERSION_MAJOR%
        echo Version.Minor : %VAR_G_INGRIDVERSION_MINOR%
        echo Version.Build : %VAR_G_INGRIDVERSION_BUILD%
        echo Version.Revision : %VAR_G_INGRIDVERSION_REVISION%
        echo .NET Version : %VAR_G_NET%
        echo Platform : %VAR_G_PLATFORM%

    - name: Pre-Build File List
      shell: cmd
      run: |
        echo File List - %GITHUB_WORKSPACE%
        cd %GITHUB_WORKSPACE%
        dir /b /s /A-D /o:gn

    - name: NuGet Restore
      run: nuget restore "${{ env.Solution_Path }}/${{ env.Solution_Name }}" -ConfigFile "${{ env.Solution_Path }}/${{ env.Solution_Nuget }}"
      shell: cmd

    # Will be continued from this line
    # Install the .NET Core workload
    - name: Install .NET Core (Version ${{ env.VAR_G_NET }})
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.VAR_G_NET }}.x
        cache: false

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Replacing BRIDGEKEY.SALT
      uses: richardrigutins/replace-in-files@v2.1.14
      with:
        files: '**/*.cs'
        search-text: 'config.GetSection("KEYS")["SALT"]'
        replacement-text: '"${{ secrets.VAR_G_SALT }}"'

    - name: Replacing BRIDGEKEY.SYNCFUSION
      uses: richardrigutins/replace-in-files@v2.1.14
      with:
        files: '**/*.cs'
        search-text: 'config.GetSection("KEYS")["SYNCFUSION"]'
        replacement-text: '"${{ secrets.VAR_G_SYNCFUSIONKEY }}"'

    - name: Replacing BRIDGEKEY.BETTERSTACK_LOG
      uses: richardrigutins/replace-in-files@v2.1.14
      with:
        files: '**/*.cs'
        search-text: 'config.GetSection("KEYS")["BETTERSTACK_LOG"]'
        replacement-text: '$"{{ secrets.VAR_G_BETTERSTACK_LOG }}"'

    - name: Replacing Version.Major
      uses: richardrigutins/replace-in-files@v2.1.14
      with:
        files: '**/*.vb'
        search-text: 'My.Application.Info.Version.Major'
        replacement-text: '${{ env.VAR_G_INGRIDVERSION_MAJOR }}'

    - name: Replacing Version.Minor
      uses: richardrigutins/replace-in-files@v2.1.14
      with:
        files: '**/*.vb'
        search-text: 'My.Application.Info.Version.Minor'
        replacement-text: '${{ env.VAR_G_INGRIDVERSION_MINOR }}'

    - name: Replacing Version.Build
      uses: richardrigutins/replace-in-files@v2.1.14
      with:
        files: '**/*.vb'
        search-text: 'My.Application.Info.Version.Build'
        replacement-text: '${{ env.VAR_G_INGRIDVERSION_BUILD }}'

    - name: Replacing Version.Revision
      uses: richardrigutins/replace-in-files@v2.1.14
      with:
        files: '**/*.vb'
        search-text: 'My.Application.Info.Version.Revision'
        replacement-text: '${{ env.VAR_G_INGRIDVERSION_REVISION }}'

    - name: Replacing Download Center URL
      uses: richardrigutins/replace-in-files@v2.1.14
      with:
        files: '**/*.vb'
        search-text: 'My.Settings.ConnectionURL'
        replacement-text: '"${{ env.VAR_G_DOWNLOADCENTER_URL }}"'

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      #this is for standard build
      #run: msbuild "${{ env.Solution_Path }}/${{ env.Solution_Name }}" /p:Configuration="${{ env.VAR_G_BUILDCONFIGURATION }}" /p:Platform=${{ env.VAR_G_PLATFORM }} /t:Rebuild 

      #this is for clickonce publish
      run: msbuild "${{ env.Solution_Path }}/${{ env.Solution_Name }}" /p:Configuration="${{ env.VAR_G_BUILDCONFIGURATION }}" /p:Platform="${{ env.VAR_G_PLATFORM }}" /t:Publish  /p:BootstrapperEnabled=True /p:IsWebBootstrapper=True /p:PublishProtocol=ClickOnce /p:Install=True /p:CreateDesktopShortcut=True /p:InstallFrom=Web /p:GenerateManifests=True /p:BootstrapperComponents="Microsoft.NetCore.DesktopRuntime.${{ env.VAR_G_NET }}.x86" /p:InstallUrl="https://ingrid-blob.s3.us-west-004.backblazeb2.com/files/" /p:PublishProfile="${{ github.workspace }}\Ingrid\Apps\Components\Ingrid-Launcher\My Project\PublishProfiles\ClickOnceProfile.pubxml" /p:PublishUrl="${{ github.workspace }}\Ingrid\Apps\Components\Ingrid-Launcher\bin\${{ env.VAR_G_BUILDCONFIGURATION }}\net${{ env.VAR_G_NET }}.0-windows\package\" /p:PublishDir="${{ github.workspace }}\Ingrid\Apps\Components\Ingrid-Launcher\bin\${{ env.VAR_G_BUILDCONFIGURATION }}\net${{ env.VAR_G_NET }}.0-windows\publish\" /p:ApplicationVersion="${{ env.VAR_G_INGRIDVERSION_MAJOR }}.${{ env.VAR_G_INGRIDVERSION_MINOR }}.${{ env.VAR_G_INGRIDVERSION_BUILD }}.${{ env.VAR_G_INGRIDVERSION_REVISION }}"
      