# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# Important note:
# $(VAR_G_INGRIDVERSION_MAJOR) : ingrid major version
# $(VAR_G_INGRIDVERSION_MINOR) : publishing number
# $(VAR_G_INGRIDVERSION_BUILD) : build / compile number
# $(VAR_G_INGRIDVERSION_REVISION) : failed build / compile number
# $(VAR_G_NET) : .NET version
# $(VAR_G_BUILDCONFIGURATION) : build configuration (Debug/Release)
# $(VAR_G_PLATFORM) : platform configuration (Any CPU/x86/x64)

name: Release

on:
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Ingrid.sln
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      with:
        nuget-version: latest

    - name: Pre-Build File List
      shell: cmd
      run: |
        echo %$VAR_G_BUILDCONFIGURATION%
        echo File List - %GITHUB_WORKSPACE%
        cd %GITHUB_WORKSPACE%
        dir /b /s /A-D /o:gn

    - name: NuGet Restore
      run: nuget restore "${{ env.Solution_Name }}" -ConfigFile "./Apps/Core/Vb/NuGet.config"
      shell: cmd

    # Will be continued from this line
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Rebuild /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

