name: ReplacingText

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
     
      - uses: actions/checkout@main
     
      - name: Find and Replace
        uses: thiagodnf/string-replacer@v1.0.2
        with:
          find: '= V_BRIDGE_KEY.SYNCFUSION()'
          replace: '= Test'
          include: |
            Apps/**/*.vb
          exclude: |
            .git/**
            node_modules/**
